export {
  AccordionRoot as Root,
  AccordionItem as Item,
  AccordionHeader as Header,
  AccordionTrigger as Trigger,
  AccordionContent as Content,
  AccordionBody as Body,
  AccordionTitle as Title,
  AccordionDescription as Description,
  AccordionPrefix as Prefix,
  AccordionSuffixIcon as SuffixIcon,
  type AccordionRootProps as RootProps,
  type AccordionItemProps as ItemProps,
  type AccordionHeaderProps as HeaderProps,
  type AccordionTriggerProps as TriggerProps,
  type AccordionContentProps as ContentProps,
  type AccordionBodyProps as BodyProps,
  type AccordionTitleProps as TitleProps,
  type AccordionDescriptionProps as DescriptionProps,
  type AccordionPrefixProps as PrefixProps,
  type AccordionSuffixIconProps as SuffixIconProps,
} from "./Accordion";
