export {
  AccordionRoot,
  AccordionItem,
  AccordionHeader,
  AccordionTrigger,
  AccordionContent,
  AccordionBody,
  AccordionTitle,
  AccordionDescription,
  AccordionPrefix,
  AccordionPrefixIcon,
  AccordionSuffixIcon,
  type AccordionRootProps,
  type AccordionItemProps,
  type AccordionHeaderProps,
  type AccordionTriggerProps,
  type AccordionContentProps,
  type AccordionBodyProps,
  type AccordionTitleProps,
  type AccordionDescriptionProps,
  type AccordionPrefixProps,
  type AccordionPrefixIconProps,
  type AccordionSuffixIconProps,
} from "./Accordion";

export * as Accordion from "./Accordion.namespace";
