export {
  AccordionRoot,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
  AccordionContentInner,
  AccordionBody,
  AccordionTitle,
  AccordionDescription,
  AccordionPrefixIcon,
  AccordionPrefixAvatar,
  AccordionSuffixIcon,
  type AccordionRootProps,
  type AccordionItemProps,
  type AccordionTriggerProps,
  type AccordionContentProps,
  type AccordionContentInnerProps,
  type AccordionBodyProps,
  type AccordionTitleProps,
  type AccordionDescriptionProps,
  type AccordionPrefixIconProps,
  type AccordionPrefixAvatarProps,
  type AccordionSuffixIconProps,
} from "./Accordion";

export * as Accordion from "./Accordion.namespace";
