#!/usr/bin/env bash

FILE_PATH=$(jq -r '.tool_input.file_path // .tool_input.filePath // .tool_input.path // empty')

if [[ "$FILE_PATH" == *".changeset/"* ]]; then
  cat >&2 <<'EOF'

You are trying to edit/add a file in the .changeset folder, which should be generated by the `bun run changeset add` command. However, `changeset add` requires an interactive shell to run and you can only 'see' the packages that can be included in the changeset. So, do the following:

1. Run `bun run changeset add` for the user (even though you can't interact with it, it'll show you the list of packages that can be included in the changeset). This should be done REGARDLESS OF if you've already asked the user which packages they want to include or not. This is because the user might have made a mistake and included a package that can't be included in the changeset (e.g. it's a private package that's only used internally), or they might have forgotten to include a package that can be included in the changeset. So, always run `bun run changeset add` first to get the list of packages that 'can' be included in the changeset. If you've already asked them which packages they want to include in the changeset, tell the user why you are asking it again based on the programatically obtained list.
2. AskUserQuestion to know which package(s) they want to include in the changeset and what type of change it is (patch, minor, major, don't include).
3. Run `cat` to generate a changeset file with the appropriate content based on the user's input. NEVER include packages that the user did not specify even if git diff shows that they were changed.

Example content of a changeset file:

```
---
"@seed-design/cli": minor
---

LLM 친화적 문서 링크를 위한 `docs` 명령어 추가

- 컴포넌트 및 파운데이션에 대한 문서 URL, llms.txt URL, GitHub raw 스니펫 URL을 출력하는 `seed-design docs [query]` 명령어를 추가합니다.
- 섹션/항목의 인터랙티브 선택과 쿼리를 통한 직접 검색을 모두 지원합니다.
```

EOF
  exit 2
fi
