import type { MigrateIconsOptions } from "../transforms/migrate-icons.js";

export const identifierMatchReact: MigrateIconsOptions["match"]["identifier"] = [
  { oldName: "IconAddThin", newName: "IconPlusLine" },
  { oldName: "IconAddRegular", newName: "IconPlusLine" },
  { oldName: "IconAddFill", newName: "IconPlusFill" },
  { oldName: "IconAddCircleThin", newName: "IconPlusCircleLine" },
  { oldName: "IconAddCircleRegular", newName: "IconPlusCircleLine" },
  { oldName: "IconAddCircleFill", newName: "IconPlusCircleFill" },
  { oldName: "IconAebThin", newName: "IconCarFrontUpsideWave2ReversedUpLine" },
  { oldName: "IconAebRegular", newName: "IconCarFrontUpsideWave2ReversedUpLine" },
  { oldName: "IconAebFill", newName: "IconCarFrontUpsideWave2ReversedUpFill" },
  { oldName: "IconAiThin", newName: "IconSparkle2Line" },
  { oldName: "IconAiRegular", newName: "IconSparkle2Line" },
  { oldName: "IconAiFill", newName: "IconSparkle2Fill" },
  { oldName: "IconAndroidShareThin", newName: "IconAndroidshareLine" },
  { oldName: "IconAndroidShareRegular", newName: "IconAndroidshareLine" },
  { oldName: "IconAndroidShareFill", newName: "IconAndroidshareFill" },
  { oldName: "IconArrowThin", newName: "IconArrowUpRightLine" },
  { oldName: "IconArrowRegular", newName: "IconArrowUpRightLine" },
  { oldName: "IconArrowFill", newName: "IconArrowUpRightFill" },
  { oldName: "IconArrowDownwardThin", newName: "IconArrowDownLine" },
  { oldName: "IconArrowDownwardRegular", newName: "IconArrowDownLine" },
  { oldName: "IconArrowDownwardFill", newName: "IconArrowDownFill" },
  { oldName: "IconArrowDropDownThin", newName: "IconTriangleDownSmallLine" },
  { oldName: "IconArrowDropDownRegular", newName: "IconTriangleDownSmallLine" },
  { oldName: "IconArrowDropDownFill", newName: "IconTriangleDownSmallFill" },
  { oldName: "IconArrowDropUpThin", newName: "IconTriangleUpSmallLine" },
  { oldName: "IconArrowDropUpRegular", newName: "IconTriangleUpSmallLine" },
  { oldName: "IconArrowDropUpFill", newName: "IconTriangleUpSmallFill" },
  { oldName: "IconArrowUpwardThin", newName: "IconArrowUpLine" },
  { oldName: "IconArrowUpwardRegular", newName: "IconArrowUpLine" },
  { oldName: "IconArrowUpwardFill", newName: "IconArrowUpFill" },
  { oldName: "IconArticleThin", newName: "IconArticleLine" },
  { oldName: "IconArticleRegular", newName: "IconArticleLine" },
  { oldName: "IconArticleFill", newName: "IconArticleFill" },
  { oldName: "IconBackwardThin", newName: "IconArrowLeftLine" },
  { oldName: "IconBackwardRegular", newName: "IconArrowLeftLine" },
  { oldName: "IconBackwardFill", newName: "IconArrowLeftFill" },
  { oldName: "IconBillThin", newName: "IconReceiptLine" },
  { oldName: "IconBillRegular", newName: "IconReceiptLine" },
  { oldName: "IconBillFill", newName: "IconReceiptFill" },
  { oldName: "IconBoldThin", newName: "IconTUppercaseSerifLine", isActionRequired: true },
  { oldName: "IconBoldRegular", newName: "IconTUppercaseSerifLine", isActionRequired: true },
  { oldName: "IconBoldFill", newName: "IconTUppercaseSerifFill", isActionRequired: true },
  { oldName: "IconBookmarkThin", newName: "IconBookmarkLine" },
  { oldName: "IconBookmarkRegular", newName: "IconBookmarkLine" },
  { oldName: "IconBookmarkFill", newName: "IconBookmarkFill" },
  { oldName: "IconBookmarkListThin", newName: "IconHorizline3VerticalStarLine" },
  { oldName: "IconBookmarkListRegular", newName: "IconHorizline3VerticalStarLine" },
  { oldName: "IconBookmarkListFill", newName: "IconHorizline3VerticalStarFill" },
  { oldName: "IconCalendarThin", newName: "IconCalendarLine" },
  { oldName: "IconCalendarRegular", newName: "IconCalendarLine" },
  { oldName: "IconCalendarFill", newName: "IconCalendarFill" },
  { oldName: "IconCallThin", newName: "IconPhoneLine" },
  { oldName: "IconCallRegular", newName: "IconPhoneLine" },
  { oldName: "IconCallFill", newName: "IconPhoneFill" },
  { oldName: "IconCallDeclinedThin", newName: "IconPhoneXmarkLine" },
  { oldName: "IconCallDeclinedRegular", newName: "IconPhoneXmarkLine" },
  { oldName: "IconCallDeclinedFill", newName: "IconPhoneXmarkFill" },
  { oldName: "IconCameraThin", newName: "IconCameraLine" },
  { oldName: "IconCameraRegular", newName: "IconCameraLine" },
  { oldName: "IconCameraFill", newName: "IconCameraFill" },
  { oldName: "IconCarThin", newName: "IconCarFrontsideLine", keepForNow: true },
  { oldName: "IconCarRegular", newName: "IconCarFrontsideLine", keepForNow: true },
  { oldName: "IconCarFill", newName: "IconCarFrontsideFill", keepForNow: true },
  { oldName: "IconCarAroundViewThin", newName: "IconArrowClockwiseOvalLine" },
  { oldName: "IconCarAroundViewRegular", newName: "IconArrowClockwiseOvalLine" },
  { oldName: "IconCarAroundViewFill", newName: "IconArrowClockwiseOvalFill" },
  { oldName: "IconCarBlindSpotThin", newName: "IconCarRearUpsideWave2ReversedDownLeftLine" },
  { oldName: "IconCarBlindSpotRegular", newName: "IconCarRearUpsideWave2ReversedDownLeftLine" },
  { oldName: "IconCarBlindSpotFill", newName: "IconCarRearUpsideWave2ReversedDownLeftFill" },
  { oldName: "IconCarCruiseControlThin", newName: "IconSpeedometerLine" },
  { oldName: "IconCarCruiseControlRegular", newName: "IconSpeedometerLine" },
  { oldName: "IconCarCruiseControlFill", newName: "IconSpeedometerFill" },
  { oldName: "IconCarEpbThin", newName: "IconEpbLine" },
  { oldName: "IconCarEpbRegular", newName: "IconEpbLine" },
  { oldName: "IconCarEpbFill", newName: "IconEpbFill" },
  { oldName: "IconCarHeatedSeatThin", newName: "IconSeatLeftHeatwave2Line" },
  { oldName: "IconCarHeatedSeatRegular", newName: "IconSeatLeftHeatwave2Line" },
  { oldName: "IconCarHeatedSeatFill", newName: "IconSeatLeftHeatwave2Fill" },
  { oldName: "IconCarHeatedSteeringWheelThin", newName: "IconSteeringwheelHeatwave2Line" },
  { oldName: "IconCarHeatedSteeringWheelRegular", newName: "IconSteeringwheelHeatwave2Line" },
  { oldName: "IconCarHeatedSteeringWheelFill", newName: "IconSteeringwheelHeatwave2Fill" },
  { oldName: "IconCarLdwsThin", newName: "IconRoadlaneLine" },
  { oldName: "IconCarLdwsRegular", newName: "IconRoadlaneLine" },
  { oldName: "IconCarLdwsFill", newName: "IconRoadlaneFill" },
  { oldName: "IconCarLeatherSeatThin", newName: "IconSeatLeftLine" },
  { oldName: "IconCarLeatherSeatRegular", newName: "IconSeatLeftLine" },
  { oldName: "IconCarLeatherSeatFill", newName: "IconSeatLeftFill" },
  { oldName: "IconCarNavigationThin", newName: "IconCompassLine" },
  { oldName: "IconCarNavigationRegular", newName: "IconCompassLine" },
  { oldName: "IconCarNavigationFill", newName: "IconCompassFill" },
  { oldName: "IconCarPowerTrunkThin", newName: "IconCarRearTrunkOpenLeftsideLine" },
  { oldName: "IconCarPowerTrunkRegular", newName: "IconCarRearTrunkOpenLeftsideLine" },
  { oldName: "IconCarPowerTrunkFill", newName: "IconCarRearTrunkOpenLeftsideFill" },
  { oldName: "IconCarRearCameraThin", newName: "IconCarRearUpsideSectorDownLine" },
  { oldName: "IconCarRearCameraRegular", newName: "IconCarRearUpsideSectorDownLine" },
  { oldName: "IconCarRearCameraFill", newName: "IconCarRearUpsideSectorDownFill" },
  { oldName: "IconCarRearSensorThin", newName: "IconCarRearUpsideWave2ReversedDownLine" },
  { oldName: "IconCarRearSensorRegular", newName: "IconCarRearUpsideWave2ReversedDownLine" },
  { oldName: "IconCarRearSensorFill", newName: "IconCarRearUpsideWave2ReversedDownFill" },
  { oldName: "IconCarSmartKeyThin", newName: "IconSmartkeyLine" },
  { oldName: "IconCarSmartKeyRegular", newName: "IconSmartkeyLine" },
  { oldName: "IconCarSmartKeyFill", newName: "IconSmartkeyFill" },
  { oldName: "IconCarVentilationSeatThin", newName: "IconSeatLeftFanLine" },
  { oldName: "IconCarVentilationSeatRegular", newName: "IconSeatLeftFanLine" },
  { oldName: "IconCarVentilationSeatFill", newName: "IconSeatLeftFanFill" },
  { oldName: "IconCartThin", newName: "IconCartLine" },
  { oldName: "IconCartRegular", newName: "IconCartLine" },
  { oldName: "IconCartFill", newName: "IconCartFill" },
  { oldName: "IconCertificationThin", newName: "IconCrosshairLine" },
  { oldName: "IconCertificationRegular", newName: "IconCrosshairLine" },
  { oldName: "IconCertificationFill", newName: "IconCrosshairFill" },
  { oldName: "IconChallengeThin", newName: "IconFlagHillLine" },
  { oldName: "IconChallengeRegular", newName: "IconFlagHillLine" },
  { oldName: "IconChallengeFill", newName: "IconFlagHillFill" },
  { oldName: "IconChartThin", newName: "IconBarchartSquareLine" },
  { oldName: "IconChartRegular", newName: "IconBarchartSquareLine" },
  { oldName: "IconChartFill", newName: "IconBarchartSquareFill" },
  { oldName: "IconChatBubbleCheckThin", newName: "IconCheckmarkChatbubbleLeftLine" },
  { oldName: "IconChatBubbleCheckRegular", newName: "IconCheckmarkChatbubbleLeftLine" },
  { oldName: "IconChatBubbleCheckFill", newName: "IconCheckmarkChatbubbleLeftFill" },
  { oldName: "IconChattingThin", newName: "IconDot3HorizontalChatbubbleLeftLine" },
  { oldName: "IconChattingRegular", newName: "IconDot3HorizontalChatbubbleLeftLine" },
  { oldName: "IconChattingFill", newName: "IconDot3HorizontalChatbubbleLeftFill" },
  { oldName: "IconChattingSendThin", newName: "IconPaperplaneLine" },
  { oldName: "IconChattingSendRegular", newName: "IconPaperplaneLine" },
  { oldName: "IconChattingSendFill", newName: "IconPaperplaneFill" },
  { oldName: "IconCheckThin", newName: "IconCheckmarkLine" },
  { oldName: "IconCheckRegular", newName: "IconCheckmarkLine" },
  { oldName: "IconCheckFill", newName: "IconCheckmarkFill" },
  { oldName: "IconCheckFlowerThin", newName: "IconCheckmarkFlowerLine" },
  { oldName: "IconCheckFlowerRegular", newName: "IconCheckmarkFlowerLine" },
  { oldName: "IconCheckFlowerFill", newName: "IconCheckmarkFlowerFill" },
  { oldName: "IconChevronLeftThin", newName: "IconChevronLeftLine" },
  { oldName: "IconChevronLeftRegular", newName: "IconChevronLeftLine" },
  { oldName: "IconChevronLeftFill", newName: "IconChevronLeftFill" },
  { oldName: "IconChevronRightThin", newName: "IconChevronRightLine" },
  { oldName: "IconChevronRightRegular", newName: "IconChevronRightLine" },
  { oldName: "IconChevronRightFill", newName: "IconChevronRightFill" },
  { oldName: "IconClickThin", newName: "IconHandPointUpLine" },
  { oldName: "IconClickRegular", newName: "IconHandPointUpLine" },
  { oldName: "IconClickFill", newName: "IconHandPointUpFill" },
  { oldName: "IconClockThin", newName: "IconClockLine" },
  { oldName: "IconClockRegular", newName: "IconClockLine" },
  { oldName: "IconClockFill", newName: "IconClockFill" },
  { oldName: "IconCloseThin", newName: "IconXmarkLine" },
  { oldName: "IconCloseRegular", newName: "IconXmarkLine" },
  { oldName: "IconCloseFill", newName: "IconXmarkFill" },
  { oldName: "IconCobuyingThin", newName: "IconShoppingbag2StackedLine", isActionRequired: true },
  {
    oldName: "IconCobuyingRegular",
    newName: "IconShoppingbag2StackedLine",
    isActionRequired: true,
  },
  { oldName: "IconCobuyingFill", newName: "IconShoppingbag2StackedFill", isActionRequired: true },
  { oldName: "IconCommunityThin", newName: "IconPostLine" },
  { oldName: "IconCommunityRegular", newName: "IconPostLine" },
  { oldName: "IconCommunityFill", newName: "IconPostFill" },
  { oldName: "IconCondoThin", newName: "IconBuilding2Line" },
  { oldName: "IconCondoRegular", newName: "IconBuilding2Line" },
  { oldName: "IconCondoFill", newName: "IconBuilding2Fill" },
  { oldName: "IconConfirmationThin", newName: "IconCheckmarkShieldLine" },
  { oldName: "IconConfirmationRegular", newName: "IconCheckmarkShieldLine" },
  { oldName: "IconConfirmationFill", newName: "IconCheckmarkShieldFill" },
  { oldName: "IconConfirmationPayThin", newName: "IconWonShieldLine" },
  { oldName: "IconConfirmationPayRegular", newName: "IconWonShieldLine" },
  { oldName: "IconConfirmationPayFill", newName: "IconWonShieldFill" },
  { oldName: "IconConfirmationProfileThin", newName: "IconPersonShieldLine" },
  { oldName: "IconConfirmationProfileRegular", newName: "IconPersonShieldLine" },
  { oldName: "IconConfirmationProfileFill", newName: "IconPersonShieldFill" },
  { oldName: "IconContentsThin", newName: "IconGridHeartLine" },
  { oldName: "IconContentsRegular", newName: "IconGridHeartLine" },
  { oldName: "IconContentsFill", newName: "IconGridHeartFill" },
  { oldName: "IconConvertThin", newName: "IconArrowRightArrowLeftLine" },
  { oldName: "IconConvertRegular", newName: "IconArrowRightArrowLeftLine" },
  { oldName: "IconConvertFill", newName: "IconArrowRightArrowLeftFill" },
  { oldName: "IconCopyThin", newName: "IconSquare2StackedLine" },
  { oldName: "IconCopyRegular", newName: "IconSquare2StackedLine" },
  { oldName: "IconCopyFill", newName: "IconSquare2StackedFill" },
  { oldName: "IconCouponThin", newName: "IconCouponLine" },
  { oldName: "IconCouponRegular", newName: "IconCouponLine" },
  { oldName: "IconCouponFill", newName: "IconCouponFill" },
  { oldName: "IconCouponDownloadDoneThin", newName: "IconCheckmarkHorizlineLine" },
  { oldName: "IconCouponDownloadDoneRegular", newName: "IconCheckmarkHorizlineLine" },
  { oldName: "IconCouponDownloadDoneFill", newName: "IconCheckmarkHorizlineFill" },
  { oldName: "IconCouponUsedThin", newName: "IconCheckmarkCouponLine" },
  { oldName: "IconCouponUsedRegular", newName: "IconCheckmarkCouponLine" },
  { oldName: "IconCouponUsedFill", newName: "IconCheckmarkCouponFill" },
  { oldName: "IconDeleteKeyboardThin", newName: "IconBackspacekeyLine" },
  { oldName: "IconDeleteKeyboardRegular", newName: "IconBackspacekeyLine" },
  { oldName: "IconDeleteKeyboardFill", newName: "IconBackspacekeyFill" },
  {
    oldName: "IconDeliveryThin",
    newName: "IconTruckLine",
    isActionRequired: true,
    keepForNow: true,
  },
  {
    oldName: "IconDeliveryRegular",
    newName: "IconTruckLine",
    isActionRequired: true,
    keepForNow: true,
  },
  {
    oldName: "IconDeliveryFill",
    newName: "IconTruckFill",
    isActionRequired: true,
    keepForNow: true,
  },
  { oldName: "IconDirectionThin", newName: "IconArrowRightAngledLine" },
  { oldName: "IconDirectionRegular", newName: "IconArrowRightAngledLine" },
  { oldName: "IconDirectionFill", newName: "IconArrowRightAngledFill" },
  { oldName: "IconDownloadThin", newName: "IconArrowDownHorizlineLine" },
  { oldName: "IconDownloadRegular", newName: "IconArrowDownHorizlineLine" },
  { oldName: "IconDownloadFill", newName: "IconArrowDownHorizlineFill" },
  { oldName: "IconEditThin", newName: "IconEraserHorizlineLine" },
  { oldName: "IconEditRegular", newName: "IconEraserHorizlineLine" },
  { oldName: "IconEditFill", newName: "IconEraserHorizlineFill" },
  { oldName: "IconEmoticonThin", newName: "IconFaceSmileCircleLine" },
  { oldName: "IconEmoticonRegular", newName: "IconFaceSmileCircleLine" },
  { oldName: "IconEmoticonFill", newName: "IconFaceSmileCircleFill" },
  { oldName: "IconEmoticonBadThin", newName: "IconFaceSadCircleLine" },
  { oldName: "IconEmoticonBadRegular", newName: "IconFaceSadCircleLine" },
  { oldName: "IconEmoticonBadFill", newName: "IconFaceSadCircleFill" },
  { oldName: "IconExpandThin", newName: "IconArrowUpRightArrowDownLeftLine" },
  { oldName: "IconExpandRegular", newName: "IconArrowUpRightArrowDownLeftLine" },
  { oldName: "IconExpandFill", newName: "IconArrowUpRightArrowDownLeftFill" },
  { oldName: "IconExpandLessThin", newName: "IconChevronUpLine" },
  { oldName: "IconExpandLessRegular", newName: "IconChevronUpLine" },
  { oldName: "IconExpandLessFill", newName: "IconChevronUpFill" },
  { oldName: "IconExpandMoreThin", newName: "IconChevronDownLine" },
  { oldName: "IconExpandMoreRegular", newName: "IconChevronDownLine" },
  { oldName: "IconExpandMoreFill", newName: "IconChevronDownFill" },
  { oldName: "IconFileThin", newName: "IconPaperclipLine" },
  { oldName: "IconFileRegular", newName: "IconPaperclipLine" },
  { oldName: "IconFileFill", newName: "IconPaperclipFill" },
  { oldName: "IconFilter02Thin", newName: "IconSlider2HorizontalLine" },
  { oldName: "IconFilter02Regular", newName: "IconSlider2HorizontalLine" },
  { oldName: "IconFilter02Fill", newName: "IconSlider2HorizontalFill" },
  { oldName: "IconForwardThin", newName: "IconArrowRightLine" },
  { oldName: "IconForwardRegular", newName: "IconArrowRightLine" },
  { oldName: "IconForwardFill", newName: "IconArrowRightFill" },
  { oldName: "IconGenderThin", newName: "IconMalesymbolFemalesymbolLine" },
  { oldName: "IconGenderRegular", newName: "IconMalesymbolFemalesymbolLine" },
  { oldName: "IconGenderFill", newName: "IconMalesymbolFemalesymbolFill" },
  { oldName: "IconGlobalThin", newName: "IconGlobeLine" },
  { oldName: "IconGlobalRegular", newName: "IconGlobeLine" },
  { oldName: "IconGlobalFill", newName: "IconGlobeFill" },
  { oldName: "IconGpsThin", newName: "IconCrosshairLine" },
  { oldName: "IconGpsRegular", newName: "IconCrosshairLine" },
  { oldName: "IconGpsFill", newName: "IconCrosshairFill" },
  { oldName: "IconGpsEnableThin", newName: "IconCrosshairQuestionmarkLine" },
  { oldName: "IconGpsEnableRegular", newName: "IconCrosshairQuestionmarkLine" },
  { oldName: "IconGpsEnableFill", newName: "IconCrosshairQuestionmarkFill" },
  { oldName: "IconGpsEnable2Thin", newName: "IconCrosshairQuestionmarkLine" },
  { oldName: "IconGpsEnable2Regular", newName: "IconCrosshairQuestionmarkLine" },
  { oldName: "IconGpsEnable2Fill", newName: "IconCrosshairQuestionmarkFill" },
  { oldName: "IconGroupchatKingThin", newName: "IconCrownLine" },
  { oldName: "IconGroupchatKingRegular", newName: "IconCrownLine" },
  { oldName: "IconGroupchatKingFill", newName: "IconCrownFill" },
  { oldName: "IconHandleThin", newName: "IconHorizline3VerticalTightLine" },
  { oldName: "IconHandleRegular", newName: "IconHorizline3VerticalTightLine" },
  { oldName: "IconHandleFill", newName: "IconHorizline3VerticalTightFill" },
  { oldName: "IconHashtagThin", newName: "IconHashLine" },
  { oldName: "IconHashtagRegular", newName: "IconHashLine" },
  { oldName: "IconHashtagFill", newName: "IconHashFill" },
  { oldName: "IconHeadphoneThin", newName: "IconHeadsetLine" },
  { oldName: "IconHeadphoneRegular", newName: "IconHeadsetLine" },
  { oldName: "IconHeadphoneFill", newName: "IconHeadsetFill" },
  { oldName: "IconHeartThin", newName: "IconHeartLine" },
  { oldName: "IconHeartRegular", newName: "IconHeartLine" },
  { oldName: "IconHeartFill", newName: "IconHeartFill" },
  { oldName: "IconHelpThin", newName: "IconQuestionmarkCircleLine" },
  { oldName: "IconHelpRegular", newName: "IconQuestionmarkCircleLine" },
  { oldName: "IconHelpFill", newName: "IconQuestionmarkCircleFill" },
  { oldName: "IconHelpcenterThin", newName: "IconHeadsetLine" },
  { oldName: "IconHelpcenterRegular", newName: "IconHeadsetLine" },
  { oldName: "IconHelpcenterFill", newName: "IconHeadsetFill" },
  { oldName: "IconHelperThin", newName: "IconHeadsetLine" },
  { oldName: "IconHelperRegular", newName: "IconHeadsetLine" },
  { oldName: "IconHelperFill", newName: "IconHeadsetFill" },
  { oldName: "IconHouseThin", newName: "IconWindow4HouseLine", keepForNow: true },
  { oldName: "IconHouseRegular", newName: "IconWindow4HouseLine", keepForNow: true },
  { oldName: "IconHouseFill", newName: "IconWindow4HouseFill", keepForNow: true },
  { oldName: "IconHomeThin", newName: "IconHouseLine" },
  { oldName: "IconHomeRegular", newName: "IconHouseLine" },
  { oldName: "IconHomeFill", newName: "IconHouseFill" },
  { oldName: "IconHousekeepingBookThin", newName: "IconBookLine" },
  { oldName: "IconHousekeepingBookRegular", newName: "IconBookLine" },
  { oldName: "IconHousekeepingBookFill", newName: "IconBookFill" },
  { oldName: "IconImportThin", newName: "IconDocumentArrowLeftLine" },
  { oldName: "IconImportRegular", newName: "IconDocumentArrowLeftLine" },
  { oldName: "IconImportFill", newName: "IconDocumentArrowLeftFill" },
  { oldName: "IconInfoThin", newName: "IconILowercaseSerifCircleLine" },
  { oldName: "IconInfoRegular", newName: "IconILowercaseSerifCircleLine" },
  { oldName: "IconInfoFill", newName: "IconILowercaseSerifCircleFill" },
  { oldName: "IconInterestThin", newName: "IconHorizline3VerticalStarLine" },
  { oldName: "IconInterestRegular", newName: "IconHorizline3VerticalStarLine" },
  { oldName: "IconInterestFill", newName: "IconHorizline3VerticalStarFill" },
  { oldName: "IconInterestListThin", newName: "IconStarLine" },
  { oldName: "IconInterestListRegular", newName: "IconStarLine" },
  { oldName: "IconInterestListFill", newName: "IconStarFill" },
  { oldName: "IconInviteThin", newName: "IconEnvelopeLine" },
  { oldName: "IconInviteRegular", newName: "IconEnvelopeLine" },
  { oldName: "IconInviteFill", newName: "IconEnvelopeFill" },
  { oldName: "IconInviteFriendThin", newName: "IconPersonPlusLine" },
  { oldName: "IconInviteFriendRegular", newName: "IconPersonPlusLine" },
  { oldName: "IconInviteFriendFill", newName: "IconPersonPlusFill" },
  { oldName: "IconIosShareThin", newName: "IconArrowUpBracketDownLine" },
  { oldName: "IconIosShareRegular", newName: "IconArrowUpBracketDownLine" },
  { oldName: "IconIosShareFill", newName: "IconArrowUpBracketDownFill" },
  { oldName: "IconJobsThin", newName: "IconPersonMagnifyingglassLine", keepForNow: true },
  { oldName: "IconJobsRegular", newName: "IconPersonMagnifyingglassLine", keepForNow: true },
  { oldName: "IconJobsFill", newName: "IconPersonMagnifyingglassFill", keepForNow: true },
  { oldName: "IconKeyboardHidingThin", newName: "IconKeyboardChevronDownLine" },
  { oldName: "IconKeyboardHidingRegular", newName: "IconKeyboardChevronDownLine" },
  { oldName: "IconKeyboardHidingFill", newName: "IconKeyboardChevronDownFill" },
  { oldName: "IconKeywordThin", newName: "IconTagLine" },
  { oldName: "IconKeywordRegular", newName: "IconTagLine" },
  { oldName: "IconKeywordFill", newName: "IconTagFill" },
  { oldName: "IconLaptopThin", newName: "IconLaptopLine" },
  { oldName: "IconLaptopRegular", newName: "IconLaptopLine" },
  { oldName: "IconLaptopFill", newName: "IconLaptopFill" },
  { oldName: "IconLeafThin", newName: "IconLeafLine" },
  { oldName: "IconLeafRegular", newName: "IconLeafLine" },
  { oldName: "IconLeafFill", newName: "IconLeafFill" },
  { oldName: "IconListThin", newName: "IconDothorizline3VerticalLine" },
  { oldName: "IconListRegular", newName: "IconDothorizline3VerticalLine" },
  { oldName: "IconListFill", newName: "IconDothorizline3VerticalFill" },
  { oldName: "IconListCardThin", newName: "IconHorizrectangleHorizline2VerticalLine" },
  { oldName: "IconListCardRegular", newName: "IconHorizrectangleHorizline2VerticalLine" },
  { oldName: "IconListCardFill", newName: "IconHorizrectangleHorizline2VerticalFill" },
  { oldName: "IconListCheckThin", newName: "IconDocumentCheckmarkLine" },
  { oldName: "IconListCheckRegular", newName: "IconDocumentCheckmarkLine" },
  { oldName: "IconListCheckFill", newName: "IconDocumentCheckmarkFill" },
  { oldName: "IconListSelectThin", newName: "IconHorizline3VerticalCheckmarkLine" },
  { oldName: "IconListSelectRegular", newName: "IconHorizline3VerticalCheckmarkLine" },
  { oldName: "IconListSelectFill", newName: "IconHorizline3VerticalCheckmarkFill" },
  { oldName: "IconListThumbnailThin", newName: "IconSquareline2VerticalLine" },
  { oldName: "IconListThumbnailRegular", newName: "IconSquareline2VerticalLine" },
  { oldName: "IconListThumbnailFill", newName: "IconSquareline2VerticalFill" },
  { oldName: "IconLocationThin", newName: "IconLocationpinLine" },
  { oldName: "IconLocationRegular", newName: "IconLocationpinLine" },
  { oldName: "IconLocationFill", newName: "IconLocationpinFill" },
  { oldName: "IconLockThin", newName: "IconLockLine" },
  { oldName: "IconLockRegular", newName: "IconLockLine" },
  { oldName: "IconLockFill", newName: "IconLockFill" },
  { oldName: "IconLoudspeakerThin", newName: "IconMegaphoneLine" },
  { oldName: "IconLoudspeakerRegular", newName: "IconMegaphoneLine" },
  { oldName: "IconLoudspeakerFill", newName: "IconMegaphoneFill" },
  { oldName: "IconMapThin", newName: "IconMapLocationpinLine" },
  { oldName: "IconMapRegular", newName: "IconMapLocationpinLine" },
  { oldName: "IconMapFill", newName: "IconMapLocationpinFill" },
  { oldName: "IconMarketThin", newName: "IconStoreLine" },
  { oldName: "IconMarketRegular", newName: "IconStoreLine" },
  { oldName: "IconMarketFill", newName: "IconStoreFill" },
  { oldName: "IconMarketCheckThin", newName: "IconStoreCheckmarkLine" },
  { oldName: "IconMarketCheckRegular", newName: "IconStoreCheckmarkLine" },
  { oldName: "IconMarketCheckFill", newName: "IconStoreCheckmarkFill" },
  { oldName: "IconMarketWriteThin", newName: "IconStorePenLine" },
  { oldName: "IconMarketWriteRegular", newName: "IconStorePenLine" },
  { oldName: "IconMarketWriteFill", newName: "IconStorePenFill" },
  { oldName: "IconMentionThin", newName: "IconAtLine" },
  { oldName: "IconMentionRegular", newName: "IconAtLine" },
  { oldName: "IconMentionFill", newName: "IconAtFill" },
  { oldName: "IconMenuThin", newName: "IconHorizline3VerticalLine" },
  { oldName: "IconMenuRegular", newName: "IconHorizline3VerticalLine" },
  { oldName: "IconMenuFill", newName: "IconHorizline3VerticalFill" },
  { oldName: "IconMicThin", newName: "IconMicrophoneLine" },
  { oldName: "IconMicRegular", newName: "IconMicrophoneLine" },
  { oldName: "IconMicFill", newName: "IconMicrophoneFill" },
  { oldName: "IconMicOffThin", newName: "IconMicrophoneSlashLine" },
  { oldName: "IconMicOffRegular", newName: "IconMicrophoneSlashLine" },
  { oldName: "IconMicOffFill", newName: "IconMicrophoneSlashFill" },
  { oldName: "IconMissionThin", newName: "IconBookOpenLine" },
  { oldName: "IconMissionRegular", newName: "IconBookOpenLine" },
  { oldName: "IconMissionFill", newName: "IconBookOpenFill" },
  { oldName: "IconMobileThin", newName: "IconMobileLine" },
  { oldName: "IconMobileRegular", newName: "IconMobileLine" },
  { oldName: "IconMobileFill", newName: "IconMobileFill" },
  { oldName: "IconMoneySendThin", newName: "IconWonCircleArrowRightLine" },
  { oldName: "IconMoneySendRegular", newName: "IconWonCircleArrowRightLine" },
  { oldName: "IconMoneySendFill", newName: "IconWonCircleArrowRightFill" },
  { oldName: "IconMoneyWonThin", newName: "IconWonCircleLine" },
  { oldName: "IconMoneyWonRegular", newName: "IconWonCircleLine" },
  { oldName: "IconMoneyWonFill", newName: "IconWonCircleFill" },
  { oldName: "IconMoonThin", newName: "IconMoonLine" },
  { oldName: "IconMoonRegular", newName: "IconMoonLine" },
  { oldName: "IconMoonFill", newName: "IconMoonFill" },
  { oldName: "IconMoreHorizThin", newName: "IconDot3HorizontalLine" },
  { oldName: "IconMoreHorizRegular", newName: "IconDot3HorizontalLine" },
  { oldName: "IconMoreHorizFill", newName: "IconDot3HorizontalFill" },
  { oldName: "IconMoreVertThin", newName: "IconDot3VerticalLine" },
  { oldName: "IconMoreVertRegular", newName: "IconDot3VerticalLine" },
  { oldName: "IconMoreVertFill", newName: "IconDot3VerticalFill" },
  { oldName: "IconMyThin", newName: "IconPersonLine" },
  { oldName: "IconMyRegular", newName: "IconPersonLine" },
  { oldName: "IconMyFill", newName: "IconPersonFill" },
  { oldName: "IconMyProfileThin", newName: "IconPersonCircleLine" },
  { oldName: "IconMyProfileRegular", newName: "IconPersonCircleLine" },
  { oldName: "IconMyProfileFill", newName: "IconPersonCircleFill" },
  { oldName: "IconNearMeThin", newName: "IconLocationpinLine" },
  { oldName: "IconNearMeRegular", newName: "IconLocationpinLine" },
  { oldName: "IconNearMeFill", newName: "IconLocationpinFill" },
  { oldName: "IconNewtopicThin", newName: "IconNUppercaseCircleLine" },
  { oldName: "IconNewtopicRegular", newName: "IconNUppercaseCircleLine" },
  { oldName: "IconNewtopicFill", newName: "IconNUppercaseCircleFill" },
  { oldName: "IconNoteThin", newName: "IconDocumentLine" },
  { oldName: "IconNoteRegular", newName: "IconDocumentLine" },
  { oldName: "IconNoteFill", newName: "IconDocumentFill" },
  { oldName: "IconNotificationThin", newName: "IconBellLine" },
  { oldName: "IconNotificationRegular", newName: "IconBellLine" },
  { oldName: "IconNotificationFill", newName: "IconBellFill" },
  { oldName: "IconNotificationFallThin", newName: "IconArrowDownLine" },
  { oldName: "IconNotificationFallRegular", newName: "IconArrowDownLine" },
  { oldName: "IconNotificationFallFill", newName: "IconArrowDownFill" },
  { oldName: "IconNotificationOffThin", newName: "IconBellSlashLine" },
  { oldName: "IconNotificationOffRegular", newName: "IconBellSlashLine" },
  { oldName: "IconNotificationOffFill", newName: "IconBellSlashFill" },
  { oldName: "IconOrderThin", newName: "IconCheckmarkClipboardLine" },
  { oldName: "IconOrderRegular", newName: "IconCheckmarkClipboardLine" },
  { oldName: "IconOrderFill", newName: "IconCheckmarkClipboardFill" },
  { oldName: "IconPauseThin", newName: "IconVertrectangle2HorizontalLine" },
  { oldName: "IconPauseRegular", newName: "IconVertrectangle2HorizontalLine" },
  { oldName: "IconPauseFill", newName: "IconVertrectangle2HorizontalFill" },
  { oldName: "IconPaymentThin", newName: "IconCardLine" },
  { oldName: "IconPaymentRegular", newName: "IconCardLine" },
  { oldName: "IconPaymentFill", newName: "IconCardFill" },
  { oldName: "IconPercentThin", newName: "IconPercentLine" },
  { oldName: "IconPercentRegular", newName: "IconPercentLine" },
  { oldName: "IconPercentFill", newName: "IconPercentFill" },
  { oldName: "IconPhotoThin", newName: "IconPictureLine" },
  { oldName: "IconPhotoRegular", newName: "IconPictureLine" },
  { oldName: "IconPhotoFill", newName: "IconPictureFill" },
  { oldName: "IconPhotoEditThin", newName: "IconWandLine" },
  { oldName: "IconPhotoEditRegular", newName: "IconWandLine" },
  { oldName: "IconPhotoEditFill", newName: "IconWandFill" },
  { oldName: "IconPhotoEditCropThin", newName: "IconCropmarkLine" },
  { oldName: "IconPhotoEditCropRegular", newName: "IconCropmarkLine" },
  { oldName: "IconPhotoEditCropFill", newName: "IconCropmarkFill" },
  { oldName: "IconPhotoEditDrawThin", newName: "IconScribbleLine" },
  { oldName: "IconPhotoEditDrawRegular", newName: "IconScribbleLine" },
  { oldName: "IconPhotoEditDrawFill", newName: "IconScribbleFill" },
  { oldName: "IconPhotoEditRotateThin", newName: "IconArrow2ClockwiseCircularLine" },
  { oldName: "IconPhotoEditRotateRegular", newName: "IconArrow2ClockwiseCircularLine" },
  { oldName: "IconPhotoEditRotateFill", newName: "IconArrow2ClockwiseCircularFill" },
  { oldName: "IconPhotoSeveralThin", newName: "IconPicture2StackedLine" },
  { oldName: "IconPhotoSeveralRegular", newName: "IconPicture2StackedLine" },
  { oldName: "IconPhotoSeveralFill", newName: "IconPicture2StackedFill" },
  { oldName: "IconPlayThin", newName: "IconTriangleRightLine" },
  { oldName: "IconPlayRegular", newName: "IconTriangleRightLine" },
  { oldName: "IconPlayFill", newName: "IconTriangleRightFill" },
  { oldName: "IconPollThin", newName: "IconBarchartSquareLine" },
  { oldName: "IconPollRegular", newName: "IconBarchartSquareLine" },
  { oldName: "IconPollFill", newName: "IconBarchartSquareFill" },
  { oldName: "IconPriceWonThin", newName: "IconWonLine" },
  { oldName: "IconPriceWonRegular", newName: "IconWonLine" },
  { oldName: "IconPriceWonFill", newName: "IconWonFill" },
  { oldName: "IconProductThin", newName: "IconShoppingbagLine" },
  { oldName: "IconProductRegular", newName: "IconShoppingbagLine" },
  { oldName: "IconProductFill", newName: "IconShoppingbagFill" },
  { oldName: "IconProfileThin", newName: "IconPersonLine" },
  { oldName: "IconProfileRegular", newName: "IconPersonLine" },
  { oldName: "IconProfileFill", newName: "IconPersonFill" },
  { oldName: "IconProfileBadgeThin", newName: "IconCheckmarkBadgeLine" },
  { oldName: "IconProfileBadgeRegular", newName: "IconCheckmarkBadgeLine" },
  { oldName: "IconProfileBadgeFill", newName: "IconCheckmarkBadgeFill" },
  { oldName: "IconProhibitionThin", newName: "IconSlashCircleLine" },
  { oldName: "IconProhibitionRegular", newName: "IconSlashCircleLine" },
  { oldName: "IconProhibitionFill", newName: "IconSlashCircleFill" },
  { oldName: "IconPushpinThin", newName: "IconPushpinLine" },
  { oldName: "IconPushpinRegular", newName: "IconPushpinLine" },
  { oldName: "IconPushpinFill", newName: "IconPushpinFill" },
  { oldName: "IconQuestionCheckThin", newName: "IconQuestionmarkSquareLine" },
  { oldName: "IconQuestionCheckRegular", newName: "IconQuestionmarkSquareLine" },
  { oldName: "IconQuestionCheckFill", newName: "IconQuestionmarkSquareFill" },
  { oldName: "IconRedoThin", newName: "IconArrowUturnRightLine" },
  { oldName: "IconRedoRegular", newName: "IconArrowUturnRightLine" },
  { oldName: "IconRedoFill", newName: "IconArrowUturnRightFill" },
  { oldName: "IconRefundThin", newName: "IconWonArrowClockwiseCircularLine" },
  { oldName: "IconRefundRegular", newName: "IconWonArrowClockwiseCircularLine" },
  { oldName: "IconRefundFill", newName: "IconWonArrowClockwiseCircularFill" },
  { oldName: "IconRemoveCircleThin", newName: "IconXmarkCircleLine" },
  { oldName: "IconRemoveCircleRegular", newName: "IconXmarkCircleLine" },
  { oldName: "IconRemoveCircleFill", newName: "IconXmarkCircleFill" },
  { oldName: "IconReplyThin", newName: "IconHorizline2VerticalChatbubbleRightLine" },
  { oldName: "IconReplyRegular", newName: "IconHorizline2VerticalChatbubbleRightLine" },
  { oldName: "IconReplyFill", newName: "IconHorizline2VerticalChatbubbleRightFill" },
  { oldName: "IconReplyMissionThin", newName: "IconHorizline2VerticalChatbubbleRightLine" },
  { oldName: "IconReplyMissionRegular", newName: "IconHorizline2VerticalChatbubbleRightLine" },
  { oldName: "IconReplyMissionFill", newName: "IconHorizline2VerticalChatbubbleRightFill" },
  { oldName: "IconReplyReThin", newName: "IconCornerDownLeftLine" },
  { oldName: "IconReplyReRegular", newName: "IconCornerDownLeftLine" },
  { oldName: "IconReplyReFill", newName: "IconCornerDownLeftFill" },
  { oldName: "IconReportThin", newName: "IconFlagLine" },
  { oldName: "IconReportRegular", newName: "IconFlagLine" },
  { oldName: "IconReportFill", newName: "IconFlagFill" },
  { oldName: "IconReservationThin", newName: "IconCheckmarkCalendarLine" },
  { oldName: "IconReservationRegular", newName: "IconCheckmarkCalendarLine" },
  { oldName: "IconReservationFill", newName: "IconCheckmarkCalendarFill" },
  { oldName: "IconRestaurantThin", newName: "IconForkSpoonLine", keepForNow: true },
  { oldName: "IconRestaurantRegular", newName: "IconForkSpoonLine", keepForNow: true },
  { oldName: "IconRestaurantFill", newName: "IconForkSpoonFill", keepForNow: true },
  { oldName: "IconRetryThin", newName: "IconArrowClockwiseCircularLine" },
  { oldName: "IconRetryRegular", newName: "IconArrowClockwiseCircularLine" },
  { oldName: "IconRetryFill", newName: "IconArrowClockwiseCircularFill" },
  { oldName: "IconReviewStarThin", newName: "IconStarLine" },
  { oldName: "IconReviewStarRegular", newName: "IconStarLine" },
  { oldName: "IconReviewStarFill", newName: "IconStarFill" },
  { oldName: "IconScannerThin", newName: "IconHorizlineViewfinderLine" },
  { oldName: "IconScannerRegular", newName: "IconHorizlineViewfinderLine" },
  { oldName: "IconScannerFill", newName: "IconHorizlineViewfinderFill" },
  { oldName: "IconSearchThin", newName: "IconMagnifyingglassLine" },
  { oldName: "IconSearchRegular", newName: "IconMagnifyingglassLine" },
  { oldName: "IconSearchFill", newName: "IconMagnifyingglassFill" },
  { oldName: "IconSearchDocThin", newName: "IconDocumentMagnifyingglassLine" },
  { oldName: "IconSearchDocRegular", newName: "IconDocumentMagnifyingglassLine" },
  { oldName: "IconSearchDocFill", newName: "IconDocumentMagnifyingglassFill" },
  { oldName: "IconSellThin", newName: "IconPlusSquareLine" },
  { oldName: "IconSellRegular", newName: "IconPlusSquareLine" },
  { oldName: "IconSellFill", newName: "IconPlusSquareFill" },
  { oldName: "IconSettingThin", newName: "IconGearLine" },
  { oldName: "IconSettingRegular", newName: "IconGearLine" },
  { oldName: "IconSettingFill", newName: "IconGearFill" },
  { oldName: "IconSignoutThin", newName: "IconBracketLeftArrowRightLine" },
  { oldName: "IconSignoutRegular", newName: "IconBracketLeftArrowRightLine" },
  { oldName: "IconSignoutFill", newName: "IconBracketLeftArrowRightFill" },
  { oldName: "IconSortThin", newName: "IconArrowUpArrowDownLine" },
  { oldName: "IconSortRegular", newName: "IconArrowUpArrowDownLine" },
  { oldName: "IconSortFill", newName: "IconArrowUpArrowDownFill" },
  { oldName: "IconStoryThin", newName: "IconTriangleRightChatbubbleLeftLine", keepForNow: true },
  { oldName: "IconStoryRegular", newName: "IconTriangleRightChatbubbleLeftLine", keepForNow: true },
  { oldName: "IconStoryFill", newName: "IconTriangleRightChatbubbleLeftFill", keepForNow: true },
  { oldName: "IconStoryArticleThin", newName: "IconDocumentPenLine" },
  { oldName: "IconStoryArticleRegular", newName: "IconDocumentPenLine" },
  { oldName: "IconStoryArticleFill", newName: "IconDocumentPenFill" },
  { oldName: "IconSubtractCircleThin", newName: "IconMinusCircleLine" },
  { oldName: "IconSubtractCircleRegular", newName: "IconMinusCircleLine" },
  { oldName: "IconSubtractCircleFill", newName: "IconMinusCircleFill" },
  { oldName: "IconSubtractionThin", newName: "IconMinusLine" },
  { oldName: "IconSubtractionRegular", newName: "IconMinusLine" },
  { oldName: "IconSubtractionFill", newName: "IconMinusFill" },
  { oldName: "IconSuggestThin", newName: "IconLightbulbDot5Line", isActionRequired: true },
  { oldName: "IconSuggestRegular", newName: "IconLightbulbDot5Line", isActionRequired: true },
  { oldName: "IconSuggestFill", newName: "IconLightbulbDot5Fill", isActionRequired: true },
  { oldName: "IconSunThin", newName: "IconSunLine" },
  { oldName: "IconSunRegular", newName: "IconSunLine" },
  { oldName: "IconSunFill", newName: "IconSunFill" },
  { oldName: "IconTalkingdownThin", newName: "IconQuotationmark2RightLine" },
  { oldName: "IconTalkingdownRegular", newName: "IconQuotationmark2RightLine" },
  { oldName: "IconTalkingdownFill", newName: "IconQuotationmark2RightFill" },
  { oldName: "IconTalkingupThin", newName: "IconQuotationmark2LeftLine" },
  { oldName: "IconTalkingupRegular", newName: "IconQuotationmark2LeftLine" },
  { oldName: "IconTalkingupFill", newName: "IconQuotationmark2LeftFill" },
  { oldName: "IconTextThin", newName: "IconTUppercaseSerifLine" },
  { oldName: "IconTextRegular", newName: "IconTUppercaseSerifLine" },
  { oldName: "IconTextFill", newName: "IconTUppercaseSerifFill" },
  { oldName: "IconThumbDownThin", newName: "IconThumbDownLine" },
  { oldName: "IconThumbDownRegular", newName: "IconThumbDownLine" },
  { oldName: "IconThumbDownFill", newName: "IconThumbDownFill" },
  { oldName: "IconThumbUpThin", newName: "IconThumbUpLine" },
  { oldName: "IconThumbUpRegular", newName: "IconThumbUpLine" },
  { oldName: "IconThumbUpFill", newName: "IconThumbUpFill" },
  { oldName: "IconToolboxThin", newName: "IconToolboxLine" },
  { oldName: "IconToolboxRegular", newName: "IconToolboxLine" },
  { oldName: "IconToolboxFill", newName: "IconToolboxFill" },
  { oldName: "IconTranslateThin", newName: "IconTranslationLine" },
  { oldName: "IconTranslateRegular", newName: "IconTranslationLine" },
  { oldName: "IconTranslateFill", newName: "IconTranslationFill" },
  { oldName: "IconTrashThin", newName: "IconTrashcanLine" },
  { oldName: "IconTrashRegular", newName: "IconTrashcanLine" },
  { oldName: "IconTrashFill", newName: "IconTrashcanFill" },
  { oldName: "IconUndoThin", newName: "IconArrowUturnLeftLine" },
  { oldName: "IconUndoRegular", newName: "IconArrowUturnLeftLine" },
  { oldName: "IconUndoFill", newName: "IconArrowUturnLeftFill" },
  { oldName: "IconUserGroupThin", newName: "IconPerson2Line" },
  { oldName: "IconUserGroupRegular", newName: "IconPerson2Line" },
  { oldName: "IconUserGroupFill", newName: "IconPerson2Fill" },
  { oldName: "IconVideoThin", newName: "IconCamcorderLine" },
  { oldName: "IconVideoRegular", newName: "IconCamcorderLine" },
  { oldName: "IconVideoFill", newName: "IconCamcorderFill" },
  { oldName: "IconViewCountThin", newName: "IconEyeLine" },
  { oldName: "IconViewCountRegular", newName: "IconEyeLine" },
  { oldName: "IconViewCountFill", newName: "IconEyeFill" },
  { oldName: "IconViewCountOffThin", newName: "IconEyeSlashLine" },
  { oldName: "IconViewCountOffRegular", newName: "IconEyeSlashLine" },
  { oldName: "IconViewCountOffFill", newName: "IconEyeSlashFill" },
  { oldName: "IconVolumeOffThin", newName: "IconSpeakerSlashLine" },
  { oldName: "IconVolumeOffRegular", newName: "IconSpeakerSlashLine" },
  { oldName: "IconVolumeOffFill", newName: "IconSpeakerSlashFill" },
  { oldName: "IconVolumeOnThin", newName: "IconSpeakerWave2Line" },
  { oldName: "IconVolumeOnRegular", newName: "IconSpeakerWave2Line" },
  { oldName: "IconVolumeOnFill", newName: "IconSpeakerWave2Fill" },
  { oldName: "IconVoteThin", newName: "IconCheckmarkBallotboxLine" },
  { oldName: "IconVoteRegular", newName: "IconCheckmarkBallotboxLine" },
  { oldName: "IconVoteFill", newName: "IconCheckmarkBallotboxFill" },
  { oldName: "IconVoucherThin", newName: "IconGiftLine" },
  { oldName: "IconVoucherRegular", newName: "IconGiftLine" },
  { oldName: "IconVoucherFill", newName: "IconGiftFill" },
  { oldName: "IconWalkThin", newName: "IconFigureWalkLine" },
  { oldName: "IconWalkRegular", newName: "IconFigureWalkLine" },
  { oldName: "IconWalkFill", newName: "IconFigureWalkFill" },
  { oldName: "IconWarningThin", newName: "IconExclamationmarkCircleLine" },
  { oldName: "IconWarningRegular", newName: "IconExclamationmarkCircleLine" },
  { oldName: "IconWarningFill", newName: "IconExclamationmarkCircleFill" },
  { oldName: "IconWriteThin", newName: "IconPenHorizlineLine" },
  { oldName: "IconWriteRegular", newName: "IconPenHorizlineLine" },
  { oldName: "IconWriteFill", newName: "IconPenHorizlineFill" },
  { oldName: "IconWriteFrequentUseThin", newName: "IconDocumentPlusLine" },
  { oldName: "IconWriteFrequentUseRegular", newName: "IconDocumentPlusLine" },
  { oldName: "IconWriteFrequentUseFill", newName: "IconDocumentPlusFill" },
  {
    oldName: "IconWriteStoryThin",
    newName: "IconHorizline2VerticalChatbubbleRightLine",
    isActionRequired: true,
  },
  {
    oldName: "IconWriteStoryRegular",
    newName: "IconHorizline2VerticalChatbubbleRightLine",
    isActionRequired: true,
  },
  {
    oldName: "IconWriteStoryFill",
    newName: "IconHorizline2VerticalChatbubbleRightFill",
    isActionRequired: true,
  },
];
