export {
  AlertDialogAction as Action,
  AlertDialogBackdrop as Backdrop,
  AlertDialogContent as Content,
  AlertDialogDescription as Description,
  AlertDialogFooter as Footer,
  AlertDialogHeader as Header,
  AlertDialogPositioner as Positioner,
  AlertDialogRoot as Root,
  AlertDialogTitle as Title,
  AlertDialogTrigger as Trigger,
  type AlertDialogActionProps as ActionProps,
  type AlertDialogBackdropProps as BackdropProps,
  type AlertDialogContentProps as ContentProps,
  type AlertDialogDescriptionProps as DescriptionProps,
  type AlertDialogFooterProps as FooterProps,
  type AlertDialogHeaderProps as HeaderProps,
  type AlertDialogPositionerProps as PositionerProps,
  type AlertDialogRootProps as RootProps,
  type AlertDialogTitleProps as TitleProps,
  type AlertDialogTriggerProps as TriggerProps,
} from "./AlertDialog";
