yarnPath: .yarn/releases/yarn-3.1.0.cjs

nodeLinker: node-modules
nmMode: hardlinks-global

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
