changesetBaseRefs:
  - "main"
  - "origin/main"
  - "upstream/main"

packageExtensions:
  istanbul-lib-processinfo@*:
    dependencies:
      mkdirp: "*"
  tcompare@*:
    dependencies:
      diff: "*"
  treport@*:
    dependencies:
      tap-yaml: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-changed.cjs
    spec: "https://github.com/Dcard/yarn-plugins/releases/latest/download/plugin-changed.js"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
