[install]
# registry = "https://registry.npmjs.org/" # moved to .npmrc; bunfig.toml is overridden by user ~/.npmrc
linker = "isolated"
minimumReleaseAge = 259200 # 3 days
minimumReleaseAgeExcludes = ["@karrotmarket/react-monochrome-icon", "@karrotmarket/react-multicolor-icon", "@karrotmarket/icon-data"]

[test]
preload = ["./scripts/happydom.ts", "./scripts/testing-library.ts"]
