// This file is generated by scripts/generate-component-grid-manifest.ts. Do not edit manually.

export interface CatalogGridManifestEntry {
  slug: string;
  title: string;
  description: string;
}

export const catalogGridManifest: Record<string, readonly CatalogGridManifestEntry[]> = {
  "/components/": [
    {
      slug: "accordion",
      title: "Accordion",
      description: "세부 정보를 점진적으로 공개할 수 있는, 수직으로 쌓인 목록 컴포넌트입니다.",
    },
    {
      slug: "action-button",
      title: "Action Button",
      description: "명확한 액션을 쉽게 수행할 수 있도록 돕는 기본 인터랙션 컴포넌트입니다.",
    },
    {
      slug: "alert-dialog",
      title: "Alert Dialog",
      description:
        "사용자의 확인이 반드시 필요한 경우 강력한 표현 및 경고 수단으로 활용하는 컴포넌트입니다.",
    },
    {
      slug: "attachment-input",
      title: "Attachment Input",
      description:
        "사진, 영상, 파일 첨부를 다루는 입력으로, 선택, 업로드, 진행률, 실패, 삭제 상태를 관리합니다.",
    },
    {
      slug: "avatar",
      title: "Avatar",
      description: "사용자의 프로필 이미지를 표시하는 컴포넌트입니다.",
    },
    {
      slug: "badge",
      title: "Badge",
      description:
        "객체의 속성이나 상태를 시각적으로 표현하는 작은 텍스트 라벨입니다. 사용자의 주의를 끌고 콘텐츠의 빠른 인지와 탐색을 돕기 위해 사용됩니다.",
    },
    {
      slug: "bottom-navigation",
      title: "Bottom Navigation",
      description:
        "앱의 루트 페이지 하단에 고정되어 있는 네비게이션 바로, 다섯 개의 상위 탭 간 이동을 제공합니다.",
    },
    {
      slug: "bottom-sheet",
      title: "Bottom Sheet",
      description:
        "화면 하단에서 올라오는 모달 컴포넌트입니다. 추가 정보나 액션 목록을 제공하면서도 현재 컨텍스트를 유지할 때 사용됩니다.",
    },
    {
      slug: "callout",
      title: "Callout",
      description:
        "사용자에게 중요한 정보나 팁을 시각적으로 강조하여 전달하는 메시지 컴포넌트입니다.",
    },
    {
      slug: "checkbox",
      title: "Checkbox",
      description:
        "사용자가 하나 이상의 옵션을 선택할 수 있게 해주는 컴포넌트입니다. 목록에서 여러 항목을 선택하거나 약관 동의와 같은 선택적 작업에 사용됩니다.",
    },
    {
      slug: "chip",
      title: "Chip",
      description: "사용자가 선택하거나 입력하는 값을 표시하는 컴포넌트입니다.",
    },
    {
      slug: "content-placeholder",
      title: "Content Placeholder",
      description:
        "이미지나 콘텐츠가 로드되지 않았을 때, 해당 영역의 성격을 전달하는 대체 시각 요소입니다.",
    },
    {
      slug: "contextual-floating-button",
      title: "Contextual Floating Button",
      description: "화면 위에 떠 있으며 특정 상황에서만 나타나는 보조적인 동작을 위한 버튼입니다.",
    },
    {
      slug: "date-picker",
      title: "Date Picker",
      description: "캘린더에서 날짜·기간·여러 날짜를 선택할 때 사용하는 컴포넌트입니다.",
    },
    {
      slug: "dialog",
      title: "Dialog",
      description:
        "사용자의 흐름을 일시 중지시키고, 중요한 정보를 전달하거나 특정 작업을 완료하도록 강제하는 모달형 컴포넌트입니다.",
    },
    {
      slug: "divider",
      title: "Divider",
      description:
        "시각적 구분자로써 역할을 하며, 콘텐츠 간의 구획을 명확히 나누는 데 사용하는 컴포넌트입니다.",
    },
    {
      slug: "field",
      title: "Field",
      description:
        "사용자로부터 값을 입력받는 컨테이너 컴포넌트로, 일관된 레이블, 도움말, 오류 표기와 상태 피드백을 제공합니다.",
    },
    {
      slug: "floating-action-button",
      title: "Floating Action Button",
      description: "화면 상에 떠 있으며 주요 액션을 실행하는 버튼입니다.",
    },
    {
      slug: "footer",
      title: "Footer",
      description:
        "사이트 하단에서 법적 정보·정책 링크·서비스 탐색·연락처를 모아 보여주는 영역입니다.",
    },
    {
      slug: "help-bubble",
      title: "Help Bubble",
      description:
        "사용자에게 컴포넌트의 상태나 특정 기능에 대한 추가 정보를 제공하는 컴포넌트입니다.",
    },
    {
      slug: "identity-placeholder",
      title: "Identity Placeholder",
      description: "인물을 표현하는 이미지가 로드되지 않았을 때 보여지는 대체 시각 요소입니다.",
    },
    {
      slug: "image-frame",
      title: "Image Frame",
      description: "사용자가 업로드한 이미지를 표시하기 위한 컴포넌트입니다.",
    },
    {
      slug: "input-button",
      title: "Input Button",
      description:
        "입력 필드 형태의 버튼으로, 선택창이나 피커를 열 때 사용합니다. 선택이 완료되면 버튼 라벨에 선택된 값이 표시됩니다.",
    },
    {
      slug: "list",
      title: "List",
      description: "가로 행으로 구성된 콘텐츠를 표현하는 컴포넌트입니다.",
    },
    {
      slug: "manner-temp",
      title: "Manner Temp & Manner Temp Badge",
      description:
        "사용자의 매너온도를 시각적으로 표현하는 컴포넌트입니다. 신뢰도/매너 정도를 직관적으로 보여주는 데에 사용합니다.",
    },
    {
      slug: "menu",
      title: "Menu",
      description: "사용자가 취할 수 있는 선택지나 액션 리스트를 제공하는 컴포넌트입니다.",
    },
    {
      slug: "menu-sheet",
      title: "Menu Sheet",
      description: "사용자의 작업과 관련된 선택지를 제공하는 시트 형태의 컴포넌트입니다.",
    },
    {
      slug: "notification-badge",
      title: "Notification Badge",
      description:
        "아이콘, 버튼, 메뉴 등 UI 요소에 표시되어 새로운 알림이나 읽지 않은 메시지 수를 나타내는 컴포넌트입니다.",
    },
    {
      slug: "page-banner",
      title: "Page Banner",
      description:
        "페이지 상단에 위치하며 사용자에게 전체적인 상태나 중요한 메시지를 전달하는 상위 레벨 메시지 컴포넌트입니다.",
    },
    {
      slug: "progress-board",
      title: "Progress Board",
      description: "플랫폼별 컴포넌트 구현 상태를 확인합니다.",
    },
    {
      slug: "progress-circle",
      title: "Progress Circle",
      description: "작업이 진행 중임을 알리거나 작업 시간을 시각적으로 나타내는 데 사용됩니다.",
    },
    {
      slug: "quantity-picker",
      title: "Quantity Picker",
      description: "버튼으로 수치 값을 한 단계씩 늘리거나 줄일 수 있는 입력 컴포넌트입니다.",
    },
    {
      slug: "radio",
      title: "Radio",
      description: "여러 옵션 중 하나를 선택할 수 있도록 할 때 사용하는 컴포넌트입니다.",
    },
    {
      slug: "reaction-button",
      title: "Reaction Button",
      description:
        "사용자가 콘텐츠에 대한 반응을 표현할 수 있게 해주는 컴포넌트입니다. 좋아요, 관심있어요 등의 감정적 피드백을 간편하게 제공할 때 사용됩니다.",
    },
    {
      slug: "result-section",
      title: "Result Section",
      description:
        "데이터 로딩 결과, 사용자의 액션 완료 여부 등 사용자에 액션에 대한 결과를 제공하는 템플릿입니다. 주로 전체 화면이나 특정 영역을 차지하여 다음 액션을 유도하거나 현재 상황을 안내하는 역할을 합니다.",
    },
    {
      slug: "scroll-fog",
      title: "Scroll Fog",
      description:
        "스크롤 가능한 영역에서 사용자에게 추가 콘텐츠가 있음을 시각적으로 알려주는 힌트 역할을 합니다.",
    },
    {
      slug: "segmented-control",
      title: "Segmented Control",
      description:
        "여러 옵션 중 하나를 선택하여 관련 콘텐츠를 즉시 필터링하거나 전환할 때 사용하는 컴포넌트입니다.",
    },
    {
      slug: "select",
      title: "Select",
      description: "옵션 목록에서 값을 골라 Form에 제출할 때 사용하는 컴포넌트입니다.",
    },
    {
      slug: "select-box",
      title: "Select Box",
      description:
        "명확한 테두리를 가진 컨테이너를 활용하여, 정의된 목록 중 하나 이상의 옵션을 선택하는 UI 요소입니다.",
    },
    {
      slug: "side-navigation",
      title: "Side Navigation",
      description:
        "서비스의 최상위 메뉴 간 이동을 돕고 앱의 전체 구조를 탐색할 수 있게 하는 컴포넌트입니다.",
    },
    {
      slug: "side-panel",
      title: "Side Panel",
      description:
        "화면의 측면에서 슬라이드되어 나타나며, 현재 맥락을 유지한 채 상세 정보를 확인하거나 부수적인 작업을 수행하는 레이아웃 컴포넌트입니다.",
    },
    {
      slug: "skeleton",
      title: "Skeleton",
      description:
        "콘텐츠가 로딩되는 동안 이후 나타날 요소의 윤곽을 미리 보여주어 로딩 시간을 짧게 느끼게 하는 UI 요소입니다.",
    },
    {
      slug: "slider",
      title: "Slider",
      description:
        "지정된 범위 내에서 하나 또는 두 개의 값을 선택해 입력할 수 있는 컴포넌트입니다.",
    },
    {
      slug: "snackbar",
      title: "Snackbar",
      description: "화면 하단에 일시적으로 나타나 상태나 결과를 안내하는 컴포넌트입니다.",
    },
    {
      slug: "switch",
      title: "Switch",
      description: "특정 설정 및 상태를 즉시 켜거나 끌 수 있도록 하는 컴포넌트입니다.",
    },
    {
      slug: "tabs",
      title: "Tabs",
      description: "한 화면 내에서 콘텐츠를 탭 단위로 구분하여 전환할 수 있는 컴포넌트입니다.",
    },
    {
      slug: "tag-group",
      title: "Tag Group",
      description:
        "아이콘과 텍스트 태그를 수평으로 나열해 여러 속성·상태·메타데이터를 한눈에 보여주는 정보 요약 컴포넌트입니다.",
    },
    {
      slug: "text-input",
      title: "Text Input & Textarea",
      description: "사용자로부터 텍스트를 입력받는 컴포넌트입니다.",
    },
    {
      slug: "time-picker",
      title: "Time Picker",
      description: "휠을 굴려 시간(오전·오후·시·분)을 선택할 때 사용하는 컴포넌트입니다.",
    },
    {
      slug: "top-navigation",
      title: "Top Navigation",
      description: "화면 상단에 위치하여 탐색 인터페이스를 제공하는 네비게이션 컴포넌트입니다.",
    },
  ],
  "/foundations/": [
    {
      slug: "elevation",
      title: "Elevation",
      description:
        "UI 요소 간의 상대적인 깊이와 계층 구조를 시각적으로 표현하는 디자인 원칙입니다.",
    },
    {
      slug: "gradient",
      title: "Gradient",
      description:
        "그라디언트는 배경과 아이콘 등에서 입체감이나 AI 기능을 표현할 때 사용하는 색상 토큰입니다.",
    },
    {
      slug: "inclusive-design",
      title: "Inclusive Design",
      description: "SEED는 모든 사용자가 제품을 쉽게 접근하고 사용할 수 있도록 돕습니다.",
    },
    {
      slug: "international-design",
      title: "International Design",
      description: "SEED는 전 세계에서 똑같이 유용하고 가치있는 경험을 제공할 수 있도록 돕습니다.",
    },
    {
      slug: "layout",
      title: "Layout",
      description:
        "레이아웃은 제품의 콘텐츠를 구조화하고 일관된 사용자 경험을 제공하기 위한 시각적 뼈대입니다. SEED는 다양한 화면 밀도와 디바이스 환경에 대응할 수 있도록 유연한 그리드 시스템과 중단점(Breakpoint)을 제공합니다.",
    },
    {
      slug: "motion",
      title: "Motion",
      description: "모션은 유저 인터페이스의 표현력을 높이고 쉽게 사용할 수 있도록 도와줍니다.",
    },
    {
      slug: "radius",
      title: "Radius",
      description: "Radius는 컴포넌트 혹은 콘텐츠 모서리의 둥글기를 표현합니다.",
    },
    {
      slug: "spacing",
      title: "Spacing",
      description: "Spacing은 컴포넌트 혹은 콘텐츠 간의 간격을 표현합니다.",
    },
    {
      slug: "state",
      title: "State",
      description:
        "상태 표현은 컴포넌트 또는 상호작용 가능한 요소의 상태 또는 가능성을 사용자에게 전달합니다.",
    },
    {
      slug: "typography",
      title: "Typography",
      description: "타이포그래피는 콘텐츠를 명확하고 효율적으로 표현하기 위한 디자인 요소입니다.",
    },
    {
      slug: "voice-and-tone",
      title: "Voice and Tone",
      description: "당근에서 일관되게 말하는 방법을 소개합니다.",
    },
    {
      slug: "writing",
      title: "Writing",
      description: "당근에서 일관되게 글쓰는 방법을 소개합니다.",
    },
  ],
  "/patterns/": [
    {
      slug: "loading",
      title: "Loading",
      description:
        "로딩을 관리하는 데 필요한 요소, 시간에 따른 적합한 선택지와 단계별로 사용자 경험을 최적화하는 방법에 대해 소개합니다.",
    },
  ],
};
