export {
  SelectRoot,
  SelectTrigger,
  SelectValue,
  SelectPlaceholder,
  SelectPrefixIcon,
  SelectSuffixIcon,
  SelectPositioner,
  SelectContent,
  SelectScrollArea,
  SelectGroup,
  SelectGroupLabel,
  SelectItem,
  SelectItemBody,
  SelectItemLabel,
  SelectItemDescription,
  SelectItemIndicator,
  SelectHiddenSelect,
  type SelectRootProps,
  type SelectTriggerProps,
  type SelectValueProps,
  type SelectPlaceholderProps,
  type SelectPrefixIconProps,
  type SelectSuffixIconProps,
  type SelectPositionerProps,
  type SelectContentProps,
  type SelectScrollAreaProps,
  type SelectGroupProps,
  type SelectGroupLabelProps,
  type SelectItemProps,
  type SelectItemBodyProps,
  type SelectItemLabelProps,
  type SelectItemDescriptionProps,
  type SelectItemIndicatorProps,
  type SelectHiddenSelectProps,
} from "./Select";

export * as Select from "./Select.namespace";
