import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@seed-design/stylesheet/token.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-seed data-seed-scale-color="light">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
