export {
  ResponsiveDialogAction as Action,
  ResponsiveDialogBackdrop as Backdrop,
  ResponsiveDialogBody as Body,
  ResponsiveDialogContent as Content,
  ResponsiveDialogDescription as Description,
  ResponsiveDialogFooter as Footer,
  ResponsiveDialogHandle as Handle,
  ResponsiveDialogHeader as Header,
  ResponsiveDialogPositioner as Positioner,
  ResponsiveDialogRoot as Root,
  ResponsiveDialogTitle as Title,
  ResponsiveDialogTrigger as Trigger,
  ResponsiveDialogCloseButton as CloseButton,
  type ResponsiveDialogActionProps as ActionProps,
  type ResponsiveDialogBackdropProps as BackdropProps,
  type ResponsiveDialogBodyProps as BodyProps,
  type ResponsiveDialogContentProps as ContentProps,
  type ResponsiveDialogDescriptionProps as DescriptionProps,
  type ResponsiveDialogFooterProps as FooterProps,
  type ResponsiveDialogHandleProps as HandleProps,
  type ResponsiveDialogHeaderProps as HeaderProps,
  type ResponsiveDialogPositionerProps as PositionerProps,
  type ResponsiveDialogRootProps as RootProps,
  type ResponsiveDialogTitleProps as TitleProps,
  type ResponsiveDialogTriggerProps as TriggerProps,
  type ResponsiveDialogCloseButtonProps as CloseButtonProps,
} from "./ResponsiveDialog";
