import { Divider, Grid, GridItem, HStack } from "@seed-design/react";

export default function Spanning() {
  return (
    <HStack gap="x4" width="full" height="full" p="x8">
      <Grid flexGrow columns={4} gap="x2">
        <GridItem
          colSpan={2}
          display="flex"
          bg="palette.purple600"
          color="palette.purple200"
          borderRadius="r2"
          alignItems="center"
          justifyContent="center"
        >
          1
        </GridItem>
        <GridItem
          display="flex"
          bg="palette.purple300"
          color="palette.purple600"
          borderRadius="r2"
          alignItems="center"
          justifyContent="center"
        >
          2
        </GridItem>
        <GridItem
          display="flex"
          bg="palette.purple300"
          color="palette.purple600"
          borderRadius="r2"
          alignItems="center"
          justifyContent="center"
        >
          3
        </GridItem>
        <GridItem
          colSpan="full"
          display="flex"
          bg="palette.purple600"
          color="palette.purple200"
          borderRadius="r2"
          alignItems="center"
          justifyContent="center"
        >
          4
        </GridItem>
        <GridItem
          display="flex"
          bg="palette.purple300"
          color="palette.purple600"
          borderRadius="r2"
          alignItems="center"
          justifyContent="center"
        >
          5
        </GridItem>
        <GridItem
          rowSpan={2}
          display="flex"
          bg="palette.purple600"
          color="palette.purple200"
          borderRadius="r2"
          alignItems="center"
          justifyContent="center"
        >
          6
        </GridItem>
        <GridItem
          display="flex"
          bg="palette.purple300"
          color="palette.purple600"
          borderRadius="r2"
          alignItems="center"
          justifyContent="center"
        >
          7
        </GridItem>
        <GridItem
          colStart={2}
          colEnd={-1}
          display="flex"
          bg="palette.purple600"
          color="palette.purple200"
          borderRadius="r2"
          alignItems="center"
          justifyContent="center"
        >
          8
        </GridItem>
      </Grid>
      <Divider orientation="vertical" />
      <Grid flexGrow rows={4} gap="x2" autoFlow="column">
        <GridItem
          rowSpan={2}
          display="flex"
          bg="palette.green600"
          color="palette.green200"
          borderRadius="r2"
          alignItems="center"
          justifyContent="center"
        >
          1
        </GridItem>
        <GridItem
          display="flex"
          bg="palette.green300"
          color="palette.green600"
          borderRadius="r2"
          alignItems="center"
          justifyContent="center"
        >
          2
        </GridItem>
        <GridItem
          display="flex"
          bg="palette.green300"
          color="palette.green600"
          borderRadius="r2"
          alignItems="center"
          justifyContent="center"
        >
          3
        </GridItem>
        <GridItem
          rowSpan="full"
          display="flex"
          bg="palette.green600"
          color="palette.green200"
          borderRadius="r2"
          alignItems="center"
          justifyContent="center"
        >
          4
        </GridItem>
        <GridItem
          display="flex"
          bg="palette.green300"
          color="palette.green600"
          borderRadius="r2"
          alignItems="center"
          justifyContent="center"
        >
          5
        </GridItem>
        <GridItem
          colSpan={2}
          display="flex"
          bg="palette.green600"
          color="palette.green200"
          borderRadius="r2"
          alignItems="center"
          justifyContent="center"
        >
          6
        </GridItem>
        <GridItem
          display="flex"
          bg="palette.green300"
          color="palette.green600"
          borderRadius="r2"
          alignItems="center"
          justifyContent="center"
        >
          7
        </GridItem>
        <GridItem
          rowStart={2}
          rowEnd={-1}
          display="flex"
          bg="palette.green600"
          color="palette.green200"
          borderRadius="r2"
          alignItems="center"
          justifyContent="center"
        >
          8
        </GridItem>
      </Grid>
    </HStack>
  );
}
