export {
  SliderRoot as Root,
  SliderThumb as Thumb,
  SliderRange as Range,
  SliderTick as Tick,
  SliderMarker as Marker,
  SliderValueIndicatorRoot as ValueIndicatorRoot,
  SliderValueIndicatorLabel as ValueIndicatorLabel,
  type SliderRootProps as RootProps,
  type SliderThumbProps as ThumbProps,
  type SliderRangeProps as RangeProps,
  type SliderTickProps as TickProps,
  type SliderMarkerProps as MarkerProps,
  type SliderValueIndicatorRootProps as ValueIndicatorRootProps,
  type SliderValueIndicatorLabelProps as ValueIndicatorLabelProps,
} from "./Slider.jsx";
