export {
  SliderRoot,
  SliderControl,
  SliderTrack,
  SliderRange,
  SliderThumb,
  SliderHiddenInput,
  SliderTick,
  SliderMarkers,
  SliderMarker,
  SliderTooltipRoot,
  SliderTooltipArrow,
  SliderTooltipArrowTip,
  SliderTooltipLabel,
  type SliderRootProps,
  type SliderControlProps,
  type SliderTrackProps,
  type SliderRangeProps,
  type SliderThumbProps,
  type SliderHiddenInputProps,
  type SliderTickProps,
  type SliderMarkersProps,
  type SliderMarkerProps,
  type SliderTooltipRootProps,
  type SliderTooltipArrowProps,
  type SliderTooltipArrowTipProps,
  type SliderTooltipLabelProps,
} from "./Slider";

export * as Slider from "./Slider.namespace";
