export {
  SliderRoot as Root,
  SliderThumb as Thumb,
  SliderRange as Range,
  SliderHiddenInput as HiddenInput,
  SliderTick as Tick,
  SliderMarker as Marker,
  SliderTooltipRoot as TooltipRoot,
  SliderTooltipLabel as TooltipLabel,
  type SliderRootProps as RootProps,
  type SliderThumbProps as ThumbProps,
  type SliderRangeProps as RangeProps,
  type SliderHiddenInputProps as HiddenInputProps,
  type SliderTickProps as TickProps,
  type SliderMarkerProps as MarkerProps,
  type SliderTooltipRootProps as TooltipRootProps,
  type SliderTooltipLabelProps as TooltipLabelProps,
} from "./Slider";
