export {
  SliderRoot as Root,
  SliderThumb as Thumb,
  SliderRange as Range,
  SliderHiddenInput as HiddenInput,
  SliderTick as Tick,
  SliderMarker as Marker,
  SliderPopoverRoot as PopoverRoot,
  SliderPopoverLabel as PopoverLabel,
  type SliderRootProps as RootProps,
  type SliderThumbProps as ThumbProps,
  type SliderRangeProps as RangeProps,
  type SliderHiddenInputProps as HiddenInputProps,
  type SliderTickProps as TickProps,
  type SliderMarkerProps as MarkerProps,
  type SliderPopoverRootProps as PopoverRootProps,
  type SliderPopoverLabelProps as PopoverLabelProps,
} from "./Slider";
