export {
  DialogAction as Action,
  DialogBackdrop as Backdrop,
  DialogBody as Body,
  DialogContent as Content,
  DialogDescription as Description,
  DialogFooter as Footer,
  DialogHeader as Header,
  DialogPositioner as Positioner,
  DialogRoot as Root,
  DialogTitle as Title,
  DialogTrigger as Trigger,
  type DialogActionProps as ActionProps,
  type DialogBackdropProps as BackdropProps,
  type DialogBodyProps as BodyProps,
  type DialogContentProps as ContentProps,
  type DialogDescriptionProps as DescriptionProps,
  type DialogFooterProps as FooterProps,
  type DialogHeaderProps as HeaderProps,
  type DialogPositionerProps as PositionerProps,
  type DialogRootProps as RootProps,
  type DialogTitleProps as TitleProps,
  type DialogTriggerProps as TriggerProps,
} from "./Dialog";
