import fs from "node:fs";
import path from "node:path";

const examplesDir = path.join(import.meta.dir, "../examples");
const outputPath = path.join(import.meta.dir, "../components/example-registry.ts");

function collectExamples(dir: string, prefix = ""): string[] {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const results: string[] = [];

  for (const entry of entries) {
    const relativePath = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      results.push(...collectExamples(path.join(dir, entry.name), relativePath));
    } else if (entry.name.endsWith(".tsx")) {
      results.push(relativePath.replace(/\.tsx$/, ""));
    }
  }

  return results;
}

const examples = collectExamples(examplesDir).sort();

const lines = examples.map((name) => `  "${name}": () => import("../examples/${name}"),`);

const content = `// Auto-generated by scripts/generate-example-registry.ts
// Do not edit manually. Run: bun generate:example-registry
import type { ComponentType } from "react";

// biome-ignore lint/suspicious/noExplicitAny: relaxed to accommodate stackflow activity components
type LazyFactory = () => Promise<{ default: any }>;

const registry: Record<string, LazyFactory> = {
${lines.join("\n")}
};

export function getExampleComponent(name: string): LazyFactory | undefined {
  return registry[name];
}
`;

fs.writeFileSync(outputPath, content);
console.log(`Generated example registry with ${examples.length} entries`);
