import { existsSync, readFileSync, readdirSync } from "node:fs";
import path from "node:path";

type Frontmatter = {
  title?: string;
  description?: string;
  deprecated?: boolean;
};

type CatalogGridManifestEntry = {
  slug: string;
  title: string;
  description: string;
};

const SECTIONS = ["components", "foundations", "patterns"] as const;

function readFrontmatter(source: string): Frontmatter {
  const frontmatter = /^---\r?\n([\s\S]*?)\r?\n---/.exec(source)?.[1];
  if (!frontmatter) return {};

  const parsed: unknown = Bun.YAML.parse(frontmatter);
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return {};

  const data = parsed as Record<string, unknown>;

  return {
    title: typeof data.title === "string" ? data.title : undefined,
    description: typeof data.description === "string" ? data.description : undefined,
    deprecated: data.deprecated === true,
  };
}

function collectEntries(section: (typeof SECTIONS)[number]): CatalogGridManifestEntry[] {
  const directory = path.join(process.cwd(), "content", section);
  if (!existsSync(directory)) return [];

  const entries: CatalogGridManifestEntry[] = [];
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith(".mdx") || entry.name === "index.mdx") continue;

    const slug = entry.name.slice(0, -".mdx".length);
    const frontmatter = readFrontmatter(readFileSync(path.join(directory, entry.name), "utf8"));
    if (frontmatter.deprecated) continue;

    entries.push({
      slug,
      title: frontmatter.title ?? slug,
      description: frontmatter.description ?? "",
    });
  }

  return entries.sort((a, b) => a.slug.localeCompare(b.slug));
}

function createManifestSource(): string {
  const manifest = Object.fromEntries(
    SECTIONS.map((section) => [`/${section}/`, collectEntries(section)]),
  );

  return `// This file is generated by scripts/generate-component-grid-manifest.ts. Do not edit manually.\n\nexport interface CatalogGridManifestEntry {\n  slug: string;\n  title: string;\n  description: string;\n}\n\nexport const catalogGridManifest: Record<string, readonly CatalogGridManifestEntry[]> = ${JSON.stringify(manifest, null, 2)};\n`;
}

const outputPath = path.join(process.cwd(), "app", "_llms", "rules", "component-grid-manifest.ts");

await Bun.write(outputPath, createManifestSource());
