import { defineConfig } from "@stackflow/config";

export const config = defineConfig({
  initialActivity: () => "ActivityHome",
  activities: [
    { route: "/", name: "ActivityHome" },
    { route: "/404", name: "ActivityNotFound" },
    { route: "/pop-test", name: "ActivityPopTest" },
    { route: "/legacy-animate-false-test", name: "ActivityLegacyAnimateFalseTest" },
    { route: "/accordion", name: "ActivityAccordion" },
    { route: "/action-button", name: "ActivityActionButton" },
    { route: "/alert-dialog", name: "ActivityAlertDialog" },
    { route: "/alert-dialog-activity", name: "ActivityAlertDialogActivity" },
    { route: "/alert-dialog-step", name: "ActivityAlertDialogStep" },
    { route: "/animated-tabs", name: "ActivityAnimatedTabs" },
    { route: "/avatar-stack", name: "ActivityAvatarStack" },
    { route: "/avatar", name: "ActivityAvatar" },
    { route: "/badge", name: "ActivityBadge" },
    { route: "/bottom-sheet-activity", name: "ActivityBottomSheetActivity" },
    { route: "/bottom-sheet-input-focus", name: "ActivityBottomSheetInputFocus" },
    { route: "/bottom-sheet-step", name: "ActivityBottomSheetStep" },
    { route: "/bottom-sheet", name: "ActivityBottomSheet" },
    { route: "/bottom-sheet-modal-test", name: "ActivityBottomSheetModalTest" },
    { route: "/bottom-sheet-text-field", name: "ActivityBottomSheetTextField" },
    { route: "/bottom-sheet-keyboard-playground", name: "ActivityBottomSheetKeyboardPlayground" },
    {
      route: "/bottom-sheet-with-alert-dialog-step",
      name: "ActivityBottomSheetWithAlertDialogStep",
    },
    { route: "/nested-bottom-sheet", name: "ActivityNestedBottomSheet" },
    { route: "/checkbox", name: "ActivityCheckbox" },
    { route: "/chip-button", name: "ActivityChipButton" },
    { route: "/chip-toggle", name: "ActivityChipToggle" },
    { route: "/codegen-test", name: "ActivityCodegenTest" },
    { route: "/detail", name: "ActivityDetail" },
    { route: "/dialog", name: "ActivityDialog" },
    { route: "/e2e/image-behavior", name: "ActivityE2EImageBehavior" },
    { route: "/error-state", name: "ActivityErrorState" },
    { route: "/font-multiplier-layout", name: "ActivityFontMultiplierLayout" },
    { route: "/result-section", name: "ActivityResultSection" },
    { route: "/help-bubble", name: "ActivityHelpBubble" },
    { route: "/iacvt", name: "ActivityIacvt" },
    { route: "/iacvt-experiment", name: "ActivityIacvtExperiment" },
    { route: "/layer-bar", name: "ActivityLayerBar" },
    { route: "/list-item-button", name: "ActivityListButtonItem" },
    { route: "/list-item-check", name: "ActivityListCheckItem" },
    { route: "/list-item-link", name: "ActivityListLinkItem" },
    { route: "/list-item-radio", name: "ActivityListRadioItem" },
    { route: "/list-item-switch", name: "ActivityListSwitchItem" },
    { route: "/list-item", name: "ActivityListItem" },
    { route: "/list-image-frame", name: "ActivityListImageFrame" },
    { route: "/manner-temp-level", name: "ActivityMannerTempLevel" },
    { route: "/margin-playground", name: "ActivityMarginPlayground" },
    { route: "/menu", name: "ActivityMenu" },
    { route: "/menu-sheet", name: "ActivityMenuSheet" },
    { route: "/menu-sheet-activity", name: "ActivityMenuSheetActivity" },
    { route: "/menu-sheet-activity/simple", name: "ActivityMenuSheetSimple" },
    { route: "/menu-sheet-step", name: "ActivityMenuSheetStep" },
    { route: "/mixed-version-test", name: "ActivityMixedVersionTest" },
    { route: "/partial-dark-mode", name: "ActivityPartialDarkMode" },
    { route: "/perf-check", name: "ActivityPerfCheck" },
    { route: "/plugin-basic-ui", name: "ActivityPluginBasicUI" },
    { route: "/quantity-picker", name: "ActivityQuantityPicker" },
    { route: "/pagination", name: "ActivityPagination" },
    { route: "/radio-group", name: "ActivityRadioGroup" },
    { route: "/reaction-button", name: "ActivityReactionButton" },
    { route: "/responsive-dialog", name: "ActivityResponsiveDialog" },
    { route: "/responsive-side-panel", name: "ActivityResponsiveSidePanel" },
    { route: "/scale-feedback", name: "ActivityScaleFeedback" },
    { route: "/segmented-control", name: "ActivitySegmentedControl" },
    { route: "/select", name: "ActivitySelect" },
    { route: "/side-navigation", name: "ActivitySideNavigation" },
    { route: "/side-panel", name: "ActivitySidePanel" },
    { route: "/side-panel-activity", name: "ActivitySidePanelActivity" },
    { route: "/swipeable-menu-sheet", name: "ActivitySwipeableMenuSheet" },
    { route: "/swipeable-tabs", name: "ActivitySwipeableTabs" },
    { route: "/switch", name: "ActivitySwitch" },
    { route: "/tabs", name: "ActivityTabs" },
    { route: "/tabs-auto-height-lazy", name: "ActivityTabsAutoHeightLazy" },
    { route: "/time-picker", name: "ActivityTimePicker" },
    { route: "/wheel-picker", name: "ActivityWheelPicker" },
    { route: "/chip-tabs-scroll-fog", name: "ActivityChipTabsScrollFog" },
    { route: "/attachment-field", name: "ActivityAttachmentField" },
    { route: "/attachment-display-field", name: "ActivityAttachmentDisplayField" },
    { route: "/form", name: "ActivityForm" },
    { route: "/category-sheet", name: "ActivityCategorySheet" },
    { route: "/toggle-button", name: "ActivityToggleButton" },
    { route: "/transparent-bar", name: "ActivityTransparentBar" },
    { route: "/typography-scale", name: "ActivityTypographyScale" },

    { route: "/legacy-app-screen", name: "ActivityLegacyAppScreen" },
    { route: "/app-screen", name: "ActivityAppScreen" },
    { route: "/app-screen-gesture", name: "ActivityAppScreenGesture" },
    { route: "/app-screen-preview", name: "ActivityAppScreenPreview" },
    { route: "/app-screen-transparent", name: "ActivityAppScreenTransparent" },
    { route: "/legacy-app-screen-intersection-observer", name: "ActivityLegacyAppScreenIntersectionObserver" },
    {
      route: "/app-screen-intersection-observer",
      name: "ActivityAppScreenIntersectionObserver",
    },
    { route: "/animate-false-test", name: "ActivityAnimateFalseTest" },
    { route: "/legacy-app-screen-app-bar-customization", name: "ActivityLegacyAppScreenAppBarCustomization" },
    { route: "/alert-dialog-stackflow", name: "ActivityAlertDialogStackflow" },
    {
      route: "/result-section-cta-progress-circle",
      name: "ActivityResultSectionCtaProgressCircle",
    },
    { route: "/article-prevent-pull", name: "ActivityArticlePreventPull" },
    { route: "/article-prevent-drag", name: "ActivityArticlePreventDrag" },
    { route: "/legacy-pull-to-refresh-preview", name: "ActivityLegacyPullToRefreshPreview" },
    { route: "/pull-to-refresh-preview", name: "ActivityPullToRefreshPreview" },
    { route: "/pull-to-refresh-tabs", name: "ActivityPullToRefreshTabs" },
    { route: "/legacy-pull-to-refresh-prevent-pull", name: "ActivityLegacyPullToRefreshPreventPull" },
    {
      route: "/pull-to-refresh-prevent-pull",
      name: "ActivityPullToRefreshPreventPull",
    },

    { route: "/demo/home", name: "ActivityDemoHome" },
    { route: "/demo/article-detail", name: "ActivityDemoArticleDetail" },
  ],
  // NextAppScreen unmounts on this timer, so an exit longer than it gets cut
  // off mid-animation. 350ms is the longest exit any transitionStyle runs
  // (horizontalSlide), and any screen may opt into it regardless of theme.
  transitionDuration: 350,
});
