import { defineConfig } from "@stackflow/config";
import { theme } from "./theme";

export const config = defineConfig({
  initialActivity: () => "ActivityHome",
  activities: [
    { route: "/", name: "ActivityHome" },
    { route: "/404", name: "ActivityNotFound" },
    { route: "/action-button", name: "ActivityActionButton" },
    { route: "/alert-dialog", name: "ActivityAlertDialog" },
    { route: "/alert-dialog-activity", name: "ActivityAlertDialogActivity" },
    { route: "/alert-dialog-step", name: "ActivityAlertDialogStep" },
    { route: "/animated-tabs", name: "ActivityAnimatedTabs" },
    { route: "/avatar-stack", name: "ActivityAvatarStack" },
    { route: "/avatar", name: "ActivityAvatar" },
    { route: "/badge", name: "ActivityBadge" },
    { route: "/bottom-sheet-activity", name: "ActivityBottomSheetActivity" },
    { route: "/bottom-sheet-step", name: "ActivityBottomSheetStep" },
    { route: "/bottom-sheet", name: "ActivityBottomSheet" },
    { route: "/bottom-sheet-modal-test", name: "ActivityBottomSheetModalTest" },
    { route: "/chip-button", name: "ActivityChipButton" },
    { route: "/chip-toggle", name: "ActivityChipToggle" },
    { route: "/codegen-test", name: "ActivityCodegenTest" },
    { route: "/detail", name: "ActivityDetail" },
    { route: "/error-state", name: "ActivityErrorState" },
    { route: "/font-scaling", name: "ActivityFontScaling" },
    { route: "/result-section", name: "ActivityResultSection" },
    { route: "/help-bubble", name: "ActivityHelpBubble" },
    { route: "/layer-bar", name: "ActivityLayerBar" },
    { route: "/list-item-button", name: "ActivityListButtonItem" },
    { route: "/list-item-check", name: "ActivityListCheckItem" },
    { route: "/list-item-link", name: "ActivityListLinkItem" },
    { route: "/list-item-radio", name: "ActivityListRadioItem" },
    { route: "/list-item-switch", name: "ActivityListSwitchItem" },
    { route: "/list-item", name: "ActivityListItem" },
    { route: "/list-image-frame", name: "ActivityListImageFrame" },
    { route: "/manner-temp-level", name: "ActivityMannerTempLevel" },
    { route: "/menu-sheet", name: "ActivityMenuSheet" },
    { route: "/menu-sheet-activity", name: "ActivityMenuSheetActivity" },
    { route: "/menu-sheet-activity/simple", name: "ActivityMenuSheetSimple" },
    { route: "/menu-sheet-step", name: "ActivityMenuSheetStep" },
    { route: "/mixed-version-test", name: "ActivityMixedVersionTest" },
    { route: "/partial-dark-mode", name: "ActivityPartialDarkMode" },
    { route: "/perf-check", name: "ActivityPerfCheck" },
    { route: "/plugin-basic-ui", name: "ActivityPluginBasicUI" },
    { route: "/reaction-button", name: "ActivityReactionButton" },
    { route: "/segmented-control", name: "ActivitySegmentedControl" },
    { route: "/swipeable-tabs", name: "ActivitySwipeableTabs" },
    { route: "/tabs", name: "ActivityTabs" },
    { route: "/form", name: "ActivityForm" },
    { route: "/category-sheet", name: "ActivityCategorySheet" },
    { route: "/toggle-button", name: "ActivityToggleButton" },
    { route: "/transition-style", name: "ActivityTransitionStyle" },
    { route: "/transparent-bar", name: "ActivityTransparentBar" },

    { route: "/demo/home", name: "ActivityDemoHome" },
    { route: "/demo/article-detail", name: "ActivityDemoArticleDetail" },
  ],
  transitionDuration: theme === "cupertino" ? 350 : 300,
});
