import { defineConfig } from "@stackflow/config";

export const config = defineConfig({
  initialActivity: () => "ActivityHome",
  activities: [
    { name: "ActivityHome", route: "/" },
    { name: "ActivityActionButton", route: "/action-button" },
    { name: "ActivityChipButton", route: "/chip-button" },
    { name: "ActivityToggleButton", route: "/toggle-button" },
    { name: "ActivityChipToggle", route: "/chip-toggle" },
    { name: "ActivityHelpBubble", route: "/help-bubble" },
    { name: "ActivityLayerBar", route: "/layer-bar" },
    { name: "ActivityTransparentBar", route: "/transparent-bar" },
    { name: "ActivityAlertDialog", route: "/alert-dialog" },
    { name: "ActivityBottomSheet", route: "/bottom-sheet" },
    { name: "ActivityMenuSheet", route: "/menu-sheet" },
    { name: "ActivityErrorState", route: "/error" },
    { name: "ActivityMannerTempLevel", route: "/manner-temp-level" },
    { name: "ActivityAvatarStack", route: "/avatar-stack" },
    { name: "ActivityAvatar", route: "/avatar" },
    { name: "ActivityReactionButton", route: "/reaction-button" },
    { name: "ActivityTabs", route: "/tabs" },
    { name: "ActivitySwipeableTabs", route: "/swipeable-tabs" },
    { name: "ActivityAnimatedTabs", route: "/animated-tabs" },
    { name: "ActivitySegmentedControl", route: "/segmented-control" },
    { name: "ActivityPartialDarkMode", route: "/partial-dark-mode" },
    { name: "ActivityMixedVersionTest", route: "/mixed-version-test" },
    { name: "ActivityCodegenTest", route: "/codegen-test" },
    { name: "ActivityPerfCheck", route: "/perf-check" },
    { name: "ActivityListItem", route: "/list-item" },
    { name: "ActivityListButtonItem", route: "/list-item-button" },
    { name: "ActivityListLinkItem", route: "/list-item-link" },
    { name: "ActivityListSwitchItem", route: "/list-item-switch" },
    { name: "ActivityListCheckItem", route: "/list-item-check" },
    { name: "ActivityListRadioItem", route: "/list-item-radio" },
    { name: "ActivityNotFound", route: "/404" },
    { name: "ActivityBottomSheetExample", route: "/examples/bottom-sheet" },
    { name: "ActivityBottomSheetSimple", route: "/examples/bottom-sheet/simple" },
    { name: "ActivityBottomSheetForm", route: "/examples/bottom-sheet/form" },
    { name: "ActivityBottomSheetNested", route: "/examples/bottom-sheet/nested" },
    { name: "ActivityBottomSheetDetail", route: "/examples/bottom-sheet/detail" },
  ],
  transitionDuration: 350,
});
