export {
  PageBannerBody as Body,
  PageBannerCloseButton as CloseButton,
  PageBannerContent as Content,
  PageBannerDescription as Description,
  PageBannerButton as Button,
  PageBannerRoot as Root,
  PageBannerTitle as Title,
  type PageBannerBodyProps as BodyProps,
  type PageBannerCloseButtonProps as CloseButtonProps,
  type PageBannerContentProps as ContentProps,
  type PageBannerDescriptionProps as DescriptionProps,
  type PageBannerButtonProps as ButtonProps,
  type PageBannerRootProps as RootProps,
  type PageBannerTitleProps as TitleProps,
} from "./PageBanner";
