#!/usr/bin/env bun
/** Generate native clip paths from the React silhouettes and Rootage dimensions. */
import { readFile, writeFile } from "node:fs/promises";
import { parse } from "yaml";

const root = new URL("../", import.meta.url);
const recipe = await readFile(new URL("packages/qvism-preset/src/recipes/avatar.ts", root), "utf8");
const spec = parse(
  await readFile(new URL("packages/rootage/components/avatar.yaml", root), "utf8"),
);
const shapes = ["circle", "flower", "shield"] as const;
const sources = Object.fromEntries(
  shapes.map((shape) => {
    const svg = recipe.match(
      new RegExp(`const ${shape.toUpperCase()}_SVG_MASK =\\n  '(.*?)';`),
    )?.[1];
    if (!svg) throw new Error(`Missing React silhouette: ${shape}`);
    return [shape, svg];
  }),
);

function rectangle(size: number, reverse = false) {
  return reverse ? `M0 0V${size}H${size}V0Z` : `M0 0H${size}V${size}H0Z`;
}

// A compound nonzero path needs opposite outer/inner winding. Read the winding
// from the source instead of assuming that a future SVG edit preserves it.
function clockwise(path: string) {
  let x = 0;
  let y = 0;
  let startX = 0;
  let startY = 0;
  let area = 0;
  const line = (nx: number, ny: number) => {
    area += x * ny - nx * y;
    x = nx;
    y = ny;
  };
  for (const [, command, raw] of path.matchAll(/([MCLVZ])([^MCLVZ]*)/g)) {
    const n = raw
      .trim()
      .split(/[\s,]+/)
      .filter(Boolean)
      .map(Number);
    const arity = { M: 2, C: 6, L: 2, V: 1, Z: 0 }[command];
    if (n.length !== arity || n.some((v) => !Number.isFinite(v)))
      throw new Error("Unsupported Avatar path segment");
    if (command === "M") {
      x = startX = n[0];
      y = startY = n[1];
    }
    if (command === "L") line(n[0], n[1]);
    if (command === "V") line(x, n[0]);
    if (command === "Z") line(startX, startY);
    if (command === "C") {
      const x0 = x;
      const y0 = y;
      for (let step = 1; step <= 16; step++) {
        const t = step / 16;
        const u = 1 - t;
        line(
          u ** 3 * x0 + 3 * u ** 2 * t * n[0] + 3 * u * t ** 2 * n[2] + t ** 3 * n[4],
          u ** 3 * y0 + 3 * u ** 2 * t * n[1] + 3 * u * t ** 2 * n[3] + t ** 3 * n[5],
        );
      }
    }
  }
  if (Math.abs(area) < 1) throw new Error("Degenerate Avatar silhouette");
  return area > 0;
}

const paths: Record<string, Record<string, string>> = {};
for (const [variant, states] of Object.entries(spec.data.definitions)) {
  if (!variant.startsWith("size=")) continue;
  const { enabled } = states as {
    enabled: { root: { size: string }; badgeMask?: { size: string; offset: string } };
  };
  const size = Number.parseFloat(enabled.root.size);
  const full = `path('${rectangle(size)}')`;
  paths[size] = { none: full };
  for (const shape of shapes) {
    if (!enabled.badgeMask) {
      paths[size][shape] = full;
      continue;
    }
    const maskSize = Number.parseFloat(enabled.badgeMask.size);
    const offset = Number.parseFloat(enabled.badgeMask.offset);
    const svg = sources[shape];
    if (!svg.includes('viewBox="0 0 32 32"'))
      throw new Error("Unexpected Avatar silhouette viewBox");
    const scale = maskSize / 32;
    const coordinate = (n: string) => String(Number((Number(n) * scale + offset).toFixed(5)));
    let cutout: string;
    let reverse: boolean;
    if (shape === "circle") {
      const cx = Number(svg.match(/cx="([\d.]+)"/)?.[1]) * scale + offset;
      const cy = Number(svg.match(/cy="([\d.]+)"/)?.[1]) * scale + offset;
      const r = Number(svg.match(/ r="([\d.]+)"/)?.[1]) * scale;
      if (![cx, cy, r].every(Number.isFinite)) throw new Error("Invalid React circle");
      cutout = `M${cx + r} ${cy}A${r} ${r} 0 1 0 ${cx - r} ${cy}A${r} ${r} 0 1 0 ${cx + r} ${cy}Z`;
      reverse = false;
    } else {
      const path = svg.match(/ d="([^"]+)"/)?.[1];
      // All numbers in these absolute M/C/L/V commands are position coordinates.
      // Reject new command kinds rather than silently transforming radii/flags.
      if (!path || /[^MCLVZ\d.,\s+-]/.test(path))
        throw new Error(`Unsupported ${shape} path syntax`);
      reverse = clockwise(path);
      cutout = path.replace(/[-+]?\d*\.?\d+/g, coordinate);
    }
    // Enclose the complete silhouette, including the part outside the view.
    // The native view's overflow clips the result to its own bounds.
    paths[size][shape] =
      `path('${rectangle(Math.max(size, offset + maskSize), reverse)}${cutout}')`;
  }
}
const output = new URL("packages/lynx-qvism-preset/src/utils/avatar-badge-clip-paths.ts", root);
const source =
  "// Generated by bun scripts/generate-lynx-avatar-clip-paths.ts. Do not edit by hand.\n" +
  "// React SVG silhouettes + Rootage dimensions; opposite winding, no runtime image loading.\n" +
  `export const avatarBadgeClipPaths = ${JSON.stringify(paths, null, 2)} as const;\n`;
if (process.argv.includes("--check")) {
  if ((await readFile(output, "utf8")) !== source)
    throw new Error(
      "Avatar clip paths are stale. Run bun scripts/generate-lynx-avatar-clip-paths.ts",
    );
} else {
  await writeFile(output, source);
}
console.log(
  `${process.argv.includes("--check") ? "Checked" : "Generated"} ${Object.keys(paths).length} Avatar size entries.`,
);
