#!/usr/bin/env bun
/**
 * Rebuild Avatar's 3x PNG alpha masks from the React SVG silhouettes and Rootage dimensions.
 * Run: bun scripts/generate-lynx-avatar-masks.ts [--check]
 * Uses the sharp renderer already installed with our Lynx icon build tooling.
 */
import { createRequire } from "node:module";
import { readFile, writeFile } from "node:fs/promises";
import { parse } from "yaml";

const sharp = createRequire(
  new URL("../packages/rsbuild-plugin-lynx-icon/package.json", import.meta.url),
)("sharp");
const root = new URL("../", import.meta.url);
const reactRecipe = await readFile(
  new URL("packages/qvism-preset/src/recipes/avatar.ts", root),
  "utf8",
);
const spec = parse(
  await readFile(new URL("packages/rootage/components/avatar.yaml", root), "utf8"),
);
const shapes = ["circle", "flower", "shield"] as const;
const masks: Record<string, Record<string, string>> = {};
for (const [variant, states] of Object.entries(spec.data.definitions)) {
  const { enabled } = states as {
    enabled: { root: { size: string }; badgeMask?: { size: string; offset: string } };
  };
  if (!variant.startsWith("size=") || !enabled.badgeMask) continue;
  const size = Number.parseInt(enabled.root.size, 10);
  const maskSize = Number.parseInt(enabled.badgeMask.size, 10);
  const offset = Number.parseInt(enabled.badgeMask.offset, 10);
  masks[size] = {};
  for (const shape of shapes) {
    const match = reactRecipe.match(
      new RegExp(`const ${shape.toUpperCase()}_SVG_MASK =\\n  '(.*?)';`),
    );
    if (!match) throw new Error(`Missing React mask source: ${shape}`);
    const body = match[1]
      .replace(/^<svg[^>]*>/, "")
      .replace(/<\/svg>$/, "")
      .replaceAll('fill="white"', 'fill="black"');
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${size * 3}" height="${size * 3}" viewBox="0 0 ${size} ${size}"><defs><mask id="cutout" maskUnits="userSpaceOnUse" x="0" y="0" width="${size}" height="${size}"><rect width="${size}" height="${size}" fill="white"/><g transform="translate(${offset} ${offset}) scale(${maskSize / 32})">${body}</g></mask></defs><rect width="${size}" height="${size}" fill="white" mask="url(#cutout)"/></svg>`;
    const png = await sharp(Buffer.from(svg)).png({ compressionLevel: 9 }).toBuffer();
    masks[size][shape] = `url("data:image/png;base64,${png.toString("base64")}")`;
  }
}
const output = new URL("packages/lynx-qvism-preset/src/utils/avatar-badge-masks.ts", root);
const source =
  "// Generated by bun scripts/generate-lynx-avatar-masks.ts. Do not edit by hand.\n" +
  "// Precomposed alpha masks at 3x resolution. No runtime SVG or mask-composite.\n" +
  `export const avatarBadgeMasks = ${JSON.stringify(masks, null, 2)} as const;\n`;
if (process.argv.includes("--check")) {
  if ((await readFile(output, "utf8")) !== source) {
    throw new Error("Avatar masks are stale. Run bun scripts/generate-lynx-avatar-masks.ts");
  }
} else {
  await writeFile(output, source);
}
console.log(
  `${process.argv.includes("--check") ? "Checked" : "Generated"} ${Object.keys(masks).length * shapes.length} Avatar masks.`,
);
