/**
 * Regenerate with: bun scripts/generate-lynx-content-placeholder-assets.ts
 * Requires rsvg-convert (librsvg) and cwebp (WebP). Run rootage:generate first.
 * Source: React preset SVG geometry + resolved Rootage asset color, never copied paths/colors.
 */
import { readFile, writeFile, mkdtemp, rm } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { tmpdir } from "node:os";
import ts from "typescript";

const root = fileURLToPath(new URL("../", import.meta.url));
const sourcePath = path.join(root, "packages/react/src/components/ContentPlaceholder/presets.tsx");
const source = ts.createSourceFile(
  sourcePath,
  await readFile(sourcePath, "utf8"),
  ts.ScriptTarget.Latest,
  true,
  ts.ScriptKind.TSX,
);
let presets: ts.ObjectLiteralExpression | undefined;
function visit(node: ts.Node) {
  if (
    ts.isVariableDeclaration(node) &&
    node.name.getText(source) === "contentPlaceholderAssetPresetMap" &&
    node.initializer &&
    ts.isObjectLiteralExpression(node.initializer)
  )
    presets = node.initializer;
  ts.forEachChild(node, visit);
}
visit(source);
if (!presets) throw new Error("React ContentPlaceholder preset map not found");
const spec = JSON.parse(
  await readFile(
    path.join(root, "packages/rootage/__generated__/components/content-placeholder.json"),
    "utf8",
  ),
);
const colors = JSON.parse(
  await readFile(path.join(root, "packages/rootage/__generated__/color.json"), "utf8"),
).data.tokens;
const colorRef = spec.data.definitions.find(
  (d: { variants: object }) => Object.keys(d.variants).length === 0,
).definitions[0].slots.asset.color.value;
function resolveColor(ref: string, mode: string): string {
  if (!ref.startsWith("$")) return ref;
  const token = colors[ref];
  const value = token?.values[mode]?.value ?? token?.values.default?.value;
  if (typeof value !== "string") throw new Error(`Missing ${ref} for ${mode}`);
  return resolveColor(value, mode);
}
const dir = path.join(root, "packages/lynx-react/src/components/ContentPlaceholder");
const temporaryDir = await mkdtemp(path.join(tmpdir(), "seed-placeholder-assets-"));
try {
  const imports: string[] = [];
  const entries: string[] = [];
  for (const property of presets.properties) {
    if (!ts.isPropertyAssignment(property) || !ts.isIdentifier(property.name))
      throw new Error("Unexpected React preset definition");
    const name = property.name.text;
    let node = property.initializer;
    while (ts.isParenthesizedExpression(node)) node = node.expression;
    if (!ts.isJsxElement(node)) throw new Error(`Expected SVG for ${name}`);
    const svg = node
      .getText(source)
      .replaceAll("fillRule=", "fill-rule=")
      .replaceAll("clipRule=", "clip-rule=")
      .replace(/\s+aria-hidden="true"/, "");
    for (const theme of ["light", "dark"]) {
      const color = resolveColor(colorRef, `theme-${theme}`);
      const painted = svg.replace('fill="none"', `fill="${color}" stroke="${color}"`);
      const png = spawnSync("rsvg-convert", ["--width", "480", "--height", "480"], {
        input: painted,
      });
      if (png.status !== 0) throw new Error(`rsvg-convert: ${png.stderr}`);
      const pngPath = path.join(temporaryDir, "preset.png");
      await writeFile(pngPath, png.stdout);
      const webp = spawnSync("cwebp", ["-quiet", "-lossless", "-exact", pngPath, "-o", "-"]);
      if (webp.status !== 0) throw new Error(`cwebp: ${webp.stderr}`);

      imports.push(
        `const ${name}${theme} = "data:image/webp;base64,${webp.stdout.toString("base64")}";`,
      );
    }
    entries.push(`  ${name}: { light: ${name}light, dark: ${name}dark },`);
  }
  await writeFile(
    path.join(dir, "presets.ts"),
    `// Generated by scripts/generate-lynx-content-placeholder-assets.ts. Do not edit.\n${imports.join("\n")}\n\nexport const contentPlaceholderPresets: Record<${presets.properties
      .map((p) => p.name!.getText(source))
      .map((n) => JSON.stringify(n))
      .join(" | ")}, { light: string; dark: string }> = {\n${entries.join("\n")}\n};\n`,
  );
  console.log(`Generated ${entries.length} presets in two themes at 3x maximum display size.`);
} finally {
  await rm(temporaryDir, { recursive: true, force: true });
}
