export {
  DialogBackdrop as Backdrop,
  DialogBody as Body,
  DialogCloseButton as CloseButton,
  DialogPositioner as Positioner,
  DialogContent as Content,
  DialogDescription as Description,
  DialogFooter as Footer,
  DialogHeader as Header,
  DialogRoot as Root,
  DialogTitle as Title,
  DialogTrigger as Trigger,
  DialogAction as Action,
  type DialogBackdropProps as BackdropProps,
  type DialogBodyProps as BodyProps,
  type DialogCloseButtonProps as CloseButtonProps,
  type DialogPositionerProps as PositionerProps,
  type DialogContentProps as ContentProps,
  type DialogDescriptionProps as DescriptionProps,
  type DialogFooterProps as FooterProps,
  type DialogHeaderProps as HeaderProps,
  type DialogRootProps as RootProps,
  type DialogTitleProps as TitleProps,
  type DialogTriggerProps as TriggerProps,
  type DialogActionProps as ActionProps,
} from "./Dialog";
