export {
  DialogBackdrop as Backdrop,
  DialogPositioner as Positioner,
  DialogContent as Content,
  DialogBody as Body,
  DialogDescription as Description,
  DialogFooter as Footer,
  DialogHeader as Header,
  DialogRoot as Root,
  DialogTitle as Title,
  DialogTrigger as Trigger,
  DialogAction as Action,
  DialogCloseButton as CloseButton,
  type DialogBackdropProps as BackdropProps,
  type DialogPositionerProps as PositionerProps,
  type DialogContentProps as ContentProps,
  type DialogBodyProps as BodyProps,
  type DialogDescriptionProps as DescriptionProps,
  type DialogFooterProps as FooterProps,
  type DialogHeaderProps as HeaderProps,
  type DialogRootProps as RootProps,
  type DialogTitleProps as TitleProps,
  type DialogTriggerProps as TriggerProps,
  type DialogActionProps as ActionProps,
  type DialogCloseButtonProps as CloseButtonProps,
} from "./Dialog";
