export {
  DialogBackdrop,
  DialogPositioner,
  DialogContent,
  DialogBody,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogRoot,
  DialogTitle,
  DialogTrigger,
  DialogAction,
  DialogCloseButton,
  type DialogBackdropProps,
  type DialogPositionerProps,
  type DialogContentProps,
  type DialogBodyProps,
  type DialogDescriptionProps,
  type DialogFooterProps,
  type DialogHeaderProps,
  type DialogRootProps,
  type DialogTitleProps,
  type DialogTriggerProps,
  type DialogActionProps,
  type DialogCloseButtonProps,
} from "./Dialog";

export * as Dialog from "./Dialog.namespace";
