/* eslint-disable */
// Generated by Wrangler by running `wrangler types scripts/docs-archive/worker-configuration.d.ts --config scripts/docs-archive/wrangler.jsonc --include-runtime false --strict-vars false` (hash: 74308c605e377bea38fd2f959af04b60)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker");
  }
  interface Env {}
}
interface Env extends Cloudflare.Env {}
