/* eslint-disable */
// Generated by Wrangler by running `wrangler types scripts/docs-archive/worker-configuration.d.ts --config scripts/docs-archive/wrangler.jsonc --include-runtime false --strict-vars false` (hash: 6747345c35700a861d161d2c6adea30c)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env {
		REACT_V2_ORIGIN: string;
	}
}
interface Env extends Cloudflare.Env {}
