export {
  FormControlRoot as Root,
  FormControlHeader as Header,
  FormControlLabel as Label,
  FormControlIndicator as Indicator,
  FormControlFooter as Footer,
  FormControlDescription as Description,
  FormControlErrorIcon as ErrorIcon,
  FormControlErrorMessage as ErrorMessage,
  FormControlCharacterCountArea as CharacterCountArea,
  FormControlCharacterCount as CharacterCount,
  FormControlMaxCharacterCount as MaxCharacterCount,
  type FormControlRootProps as RootProps,
  type FormControlHeaderProps as HeaderProps,
  type FormControlLabelProps as LabelProps,
  type FormControlIndicatorProps as IndicatorProps,
  type FormControlFooterProps as FooterProps,
  type FormControlDescriptionProps as DescriptionProps,
  type FormControlErrorIconProps as ErrorIconProps,
  type FormControlErrorMessageProps as ErrorMessageProps,
  type FormControlCharacterCountAreaProps as CharacterCountAreaProps,
  type FormControlCharacterCountProps as CharacterCountProps,
  type FormControlMaxCharacterCountProps as MaxCharacterCountProps,
} from "./FormControl";
