import { datePicker as vars } from "../vars/component";
import {
  createFocusRingRestStyles,
  createFocusRingStyles,
  FOCUS_RING_TRANSITION,
} from "../utils/focus-ring";
import { onlyIcon } from "../utils/icon";
import { disabled, engaged, focusVisible, not, pseudo, selected } from "../utils/pseudo";
import { defineSlotRecipe } from "../utils/define";

const datePicker = defineSlotRecipe({
  name: "date-picker",
  slots: [
    "root",
    "header",
    "headerLabel",
    "headerChevron",
    "navigation",
    "navigationButton",
    "twoMonthHeader",
    "twoMonthLabel",
    "twoMonthNavigationButton",
    "weekdayRow",
    "weekday",
    "months",
    "month",
    "monthLabel",
    "grid",
    "weekRow",
    "dateCell",
    "dateButton",
    "dateContent",
    "emptyCell",
    "continuousScroll",
    "continuousContent",
    "wheelContainer",
    "wheelView",
    "wheelColumns",
    "wheelSelectionIndicator",
    "wheelScrollFog",
    "yearColumn",
    "monthColumn",
    "wheelItem",
    "liveRegion",
  ],
  base: {
    root: {
      width: "100%",
      minWidth: 0,
      boxSizing: "border-box",
      color: vars.base.enabled.dateContent.color,
      backgroundColor: vars.base.enabled.root.color,
    },
    header: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      height: vars.base.enabled.header.height,
    },
    headerLabel: {
      display: "inline-flex",
      alignItems: "center",
      gap: vars.base.enabled.headerLabel.gap,
      height: "100%",
      minWidth: 0,
      border: 0,
      paddingInline: vars.base.enabled.headerLabel.paddingX,
      paddingBlock: 0,
      color: vars.base.enabled.headerLabel.color,
      background: "transparent",
      fontSize: vars.base.enabled.headerLabel.fontSize,
      lineHeight: vars.base.enabled.headerLabel.lineHeight,
      fontWeight: vars.base.enabled.headerLabel.fontWeight,
      whiteSpace: "nowrap",
      textOverflow: "ellipsis",
      overflow: "hidden",
      cursor: "pointer",
      transition: FOCUS_RING_TRANSITION,
      ...createFocusRingRestStyles(),
      [pseudo(focusVisible)]: createFocusRingStyles(),
      [pseudo(disabled)]: {
        cursor: "default",
      },
    },
    headerChevron: {
      display: "inline-flex",
      width: vars.base.enabled.headerLabel.iconSize,
      height: vars.base.enabled.headerLabel.iconSize,
      flexShrink: 0,
      alignItems: "center",
      justifyContent: "center",
      ...onlyIcon({ size: vars.base.enabled.headerLabel.iconSize }),
    },
    navigation: {
      display: "flex",
      alignItems: "center",
      flexShrink: 0,
    },
    navigationButton: {
      flexShrink: 0,
    },
    twoMonthHeader: {
      position: "relative",
      display: "flex",
      height: vars.base.enabled.header.height,
      alignItems: "center",
      justifyContent: "center",
    },
    twoMonthLabel: {
      display: "flex",
      width: "100%",
      height: "100%",
      alignItems: "center",
      justifyContent: "center",
      color: vars.base.enabled.headerLabel.color,
      fontSize: vars.base.enabled.headerLabel.fontSize,
      lineHeight: vars.base.enabled.headerLabel.lineHeight,
      fontWeight: vars.base.enabled.headerLabel.fontWeight,
      whiteSpace: "nowrap",
    },
    twoMonthNavigationButton: {
      position: "absolute",
      top: "4px",
      flexShrink: 0,
      "&[data-placement='start']": {
        insetInlineStart: 0,
      },
      "&[data-placement='end']": {
        insetInlineEnd: 0,
      },
    },
    weekdayRow: {
      display: "grid",
      gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
      position: "relative",
      zIndex: 2,
      backgroundColor: vars.base.enabled.root.color,
    },
    weekday: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      height: vars.base.enabled.weekday.height,
      color: vars.base.enabled.weekday.color,
      fontSize: vars.base.enabled.weekday.fontSize,
      lineHeight: vars.base.enabled.weekday.lineHeight,
      fontWeight: vars.base.enabled.weekday.fontWeight,
    },
    months: {
      display: "grid",
      gridTemplateColumns: "minmax(0, 1fr)",
      alignItems: "start",
      minWidth: 0,
    },
    month: {
      minWidth: 0,
    },
    monthLabel: {
      display: "flex",
      alignItems: "center",
      height: vars.base.enabled.monthLabel.height,
      color: vars.base.enabled.monthLabel.color,
      fontSize: vars.base.enabled.monthLabel.fontSize,
      lineHeight: vars.base.enabled.monthLabel.lineHeight,
      fontWeight: vars.base.enabled.monthLabel.fontWeight,
    },
    grid: {
      display: "grid",
      minWidth: 0,
    },
    weekRow: {
      display: "grid",
      gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
    },
    dateCell: {
      position: "relative",
      minWidth: 0,
      minHeight: vars.base.enabled.dateCell.minHeight,
      isolation: "isolate",
      "&[data-range-complete][data-in-range]::before": {
        content: '""',
        position: "absolute",
        zIndex: -1,
        insetInline: 0,
        top: "3px",
        height: vars.base.enabled.dateVisual.size,
        backgroundColor: vars.base.enabled.rangeBackground.color,
      },
      "&[data-range-complete][data-range-start]:not([data-range-end])::before": {
        content: '""',
        position: "absolute",
        zIndex: -1,
        insetInlineStart: "50%",
        insetInlineEnd: 0,
        top: "3px",
        height: vars.base.enabled.dateVisual.size,
        backgroundColor: vars.base.enabled.rangeBackground.color,
      },
      "&[data-range-complete][data-range-end]:not([data-range-start])::before": {
        content: '""',
        position: "absolute",
        zIndex: -1,
        insetInlineStart: 0,
        insetInlineEnd: "50%",
        top: "3px",
        height: vars.base.enabled.dateVisual.size,
        backgroundColor: vars.base.enabled.rangeBackground.color,
      },
    },
    dateButton: {
      position: "relative",
      display: "flex",
      width: "100%",
      height: "100%",
      minHeight: vars.base.enabled.dateCell.minHeight,
      minWidth: 0,
      alignItems: "flex-start",
      justifyContent: "center",
      border: 0,
      padding: 0,
      color: vars.base.enabled.dateContent.color,
      background: "transparent",
      cursor: "pointer",
      font: "inherit",
      isolation: "isolate",
      "&::before": {
        content: '""',
        position: "absolute",
        zIndex: -1,
        top: "3px",
        left: "50%",
        width: vars.base.enabled.dateVisual.size,
        height: vars.base.enabled.dateVisual.size,
        borderRadius: vars.base.enabled.dateVisual.cornerRadius,
        backgroundColor: vars.base.enabled.dateVisual.color,
        transform: "translateX(-50%)",
      },
      "&::after": {
        content: '""',
        position: "absolute",
        zIndex: 2,
        top: "3px",
        left: "50%",
        width: vars.base.enabled.dateVisual.size,
        height: vars.base.enabled.dateVisual.size,
        borderRadius: vars.base.enabled.dateVisual.cornerRadius,
        pointerEvents: "none",
        transform: "translateX(-50%)",
        transition: FOCUS_RING_TRANSITION,
        ...createFocusRingRestStyles({ position: "inside" }),
      },
      "&[data-today]::before": {
        backgroundColor: vars.base.today.dateVisual.color,
      },
      [pseudo(selected, "::before")]: {
        backgroundColor: vars.base.selected.dateVisual.color,
      },
      [pseudo(selected)]: {
        color: vars.base.selected.dateContent.color,
      },
      [pseudo(not(disabled), engaged, "::before")]: {
        backgroundColor: vars.base.pressed.dateVisual.color,
      },
      [`${pseudo(not(disabled), selected, engaged)}:not([data-in-range])::before` as const]: {
        backgroundColor: vars.base.selected.dateVisual.color,
      },
      "&[data-in-range]": {
        color: vars.base.enabled.dateContent.color,
      },
      "&[data-in-range]::before": {
        backgroundColor: "transparent",
      },
      "&[data-unavailable]": {
        color: vars.base.disabled.dateContent.color,
        cursor: "not-allowed",
      },
      "&[data-unavailable] > * > :first-child": {
        textDecoration: "line-through",
      },
      [pseudo(disabled)]: {
        color: vars.base.disabled.dateContent.color,
        cursor: "default",
      },
      outline: "none",
      [pseudo(focusVisible)]: {
        "&::after": createFocusRingStyles({ position: "inside" }),
      },
    },
    dateContent: {
      position: "relative",
      zIndex: 1,
      display: "flex",
      width: "100%",
      minHeight: vars.base.enabled.dateCell.minHeight,
      minWidth: 0,
      boxSizing: "border-box",
      flexDirection: "column",
      alignItems: "center",
      gap: "3px",
      paddingTop: "3px",
      color: "inherit",
      fontSize: vars.base.enabled.dateContent.fontSize,
      lineHeight: vars.base.enabled.dateContent.lineHeight,
      fontWeight: vars.base.enabled.dateContent.fontWeight,
      fontVariantNumeric: "tabular-nums",
      "& > :first-child": {
        display: "flex",
        minHeight: vars.base.enabled.dateVisual.size,
        flexShrink: 0,
        alignItems: "center",
        justifyContent: "center",
      },
    },
    emptyCell: {
      minHeight: vars.base.enabled.dateCell.minHeight,
    },
    continuousScroll: {
      position: "relative",
      height: "100%",
      minHeight: 0,
      overflowY: "auto",
      overscrollBehavior: "contain",
      scrollbarWidth: "none",
      "&::-webkit-scrollbar": {
        display: "none",
      },
      "&::after": {
        content: '""',
        position: "sticky",
        zIndex: 3,
        bottom: 0,
        display: "block",
        width: "100%",
        height: vars.base.enabled.continuousScroll.fogHeight,
        marginTop: `calc(${vars.base.enabled.continuousScroll.fogHeight} * -1)`,
        background: `linear-gradient(to bottom, transparent, ${vars.base.enabled.root.color})`,
        pointerEvents: "none",
      },
    },
    continuousContent: {
      position: "relative",
      minWidth: 0,
    },
    wheelContainer: {
      display: "flex",
      height: vars.base.enabled.wheelContainer.height,
      alignItems: "center",
      backgroundColor: vars.base.enabled.root.color,
    },
    wheelView: {
      width: "100%",
    },
    wheelColumns: {},
    wheelSelectionIndicator: {
      borderRadius: vars.base.enabled.wheelSelectionIndicator.cornerRadius,
      backgroundColor: vars.base.enabled.wheelSelectionIndicator.color,
    },
    wheelScrollFog: {},
    yearColumn: {
      flex: "0 0 120px",
      "--seed-wheel-picker-item-justify-content": "flex-end",
      outline: "none",
      transition: FOCUS_RING_TRANSITION,
      ...createFocusRingRestStyles(),
      [pseudo(focusVisible)]: createFocusRingStyles(),
    },
    monthColumn: {
      flex: "0 0 96px",
      "--seed-wheel-picker-item-justify-content": "flex-start",
      outline: "none",
      transition: FOCUS_RING_TRANSITION,
      ...createFocusRingRestStyles(),
      [pseudo(focusVisible)]: createFocusRingStyles(),
    },
    wheelItem: {
      "--seed-wheel-picker-item-color": vars.base.enabled.wheelItem.color,
      "--seed-wheel-picker-selected-item-color": vars.base.selected.wheelItem.color,
      paddingInline: vars.base.enabled.wheelItem.paddingX,
      fontSize: vars.base.enabled.wheelItem.fontSize,
      lineHeight: vars.base.enabled.wheelItem.lineHeight,
      fontWeight: vars.base.enabled.wheelItem.fontWeight,
    },
    liveRegion: {
      position: "absolute",
      width: "1px",
      height: "1px",
      padding: 0,
      margin: "-1px",
      overflow: "hidden",
      clip: "rect(0, 0, 0, 0)",
      whiteSpace: "nowrap",
      border: 0,
    },
  },
  variants: {
    visibleRange: {
      month: {},
      twoMonths: {
        months: {
          gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
          columnGap: vars.base.enabled.months.gap,
        },
      },
      continuous: {
        root: {
          height: "100%",
          minHeight: 0,
        },
        weekdayRow: {
          position: "sticky",
          top: 0,
        },
        month: {
          paddingBottom: "16px",
        },
      },
      week: {
        weekday: {
          height: "24px",
        },
      },
    },
  },
  defaultVariants: {
    visibleRange: "month",
  },
});

export default datePicker;
