export {
  AccordionBody as Body,
  AccordionContent as Content,
  AccordionDescription as Description,
  AccordionHeader as Header,
  AccordionItem as Item,
  AccordionPrefix as Prefix,
  AccordionRoot as Root,
  AccordionSuffixIcon as SuffixIcon,
  AccordionTitle as Title,
  AccordionTrigger as Trigger,
  type AccordionBodyProps as BodyProps,
  type AccordionContentProps as ContentProps,
  type AccordionDescriptionProps as DescriptionProps,
  type AccordionHeaderProps as HeaderProps,
  type AccordionItemProps as ItemProps,
  type AccordionPrefixProps as PrefixProps,
  type AccordionRootProps as RootProps,
  type AccordionSuffixIconProps as SuffixIconProps,
  type AccordionTitleProps as TitleProps,
  type AccordionTriggerProps as TriggerProps,
} from "./Accordion";
