name: Test CLI

on:
  push:
    paths:
      - "packages/cli/**/*"
      - "packages/utils/docs-search/**/*"
      - ".github/workflows/cli-test.yml"
      - ".github/actions/setup/action.yml"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: ./.github/actions/setup

      - name: Build dependencies
        run: bun --filter @seed-design/docs-search build

      - name: Run tests
        run: bun test packages/cli
