on:
  push:
    branches:
      - "**"
      - "!main"
      - "!dev" # V3 deployment; remove this when V3 is stable

    paths:
      - "docs/**"
      - "packages/css/**"
      - "packages/react/**"
      - "packages/stackflow/**"
      - ".github/workflows/deploy-seed-design-storybook-alpha-pages.yml"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: deploy-seed-design-storybook-alpha-pages

jobs:
  deploy:
    name: deploy-seed-design-storybook-alpha-pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.8"

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build Packages
        run: bun packages:build

      - name: Build Storybook
        working-directory: ./docs
        run: bun build-storybook

      - name: Deploy docs at Cloudflare Pages in `seed-design-storybook` project (Alpha)
        run: |
          CLOUDFLARE_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }} \
          CLOUDFLARE_API_TOKEN=${{ secrets.CF_API_TOKEN }} \
          bun wrangler pages deploy ./docs/storybook-static --project-name=seed-design-storybook --branch=${{ github.ref_name }}
