name: Test Docs

on:
  push:
    paths:
      - "docs/**/*"
      - "packages/css/**"
      - "packages/lynx-react/**"
      - "packages/lynx-css/**"
      - ".github/workflows/docs-test.yml"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: ./.github/actions/setup

      - name: Build dependencies
        run: bun packages:build

      - name: Run tests
        run: bun docs:test
