name: Test E2E

on:
  push:
    paths:
      - "examples/stackflow-spa/**"
      - "docs/registry/react/**"
      - "packages/stackflow/**"
      - "packages/react/**"
      - "packages/react-headless/**"
      - "packages/css/**"
      - "packages/stylesheet/**"
      - ".github/workflows/e2e-test.yml"
      - ".github/actions/setup/action.yml"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup
        with:
          build-packages: true

      - name: Install browsers
        run: bunx playwright install --with-deps chromium webkit
        working-directory: examples/stackflow-spa

      - name: Run tests
        run: bun run e2e
        working-directory: examples/stackflow-spa

      - name: Upload report
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: playwright-report
          path: examples/stackflow-spa/playwright-report
          retention-days: 7
