name: Test React

on:
  push:
    paths:
      - "packages/react/**/*"
      - ".github/workflows/react-test.yml"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build common dependencies
        run: bun --filter @seed-design/dom-utils build && bun --filter @seed-design/react-primitive build && bun headless:build

      - name: Run tests
        run: bun react:test
