name: Release

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "packages/**"
      - "docs/**"
      - ".changeset/**"
      - ".github/workflows/release-packages.yml"
      - ".github/actions/setup/action.yml"
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release Seed Design Packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: read
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: actions/setup-node@v6 # this is faster than `bun install -g npm@latest`
        with:
          node-version: "24"

      - uses: ./.github/actions/setup

      - name: 릴리즈 Pull Request를 만들거나 패키지를 배포해요
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun release
          version: bun version
          title: "release: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          POSTHOG_HOST: ${{ secrets.POSTHOG_HOST }}

      - name: 배포된 버전을 가져와요
        id: get-package-versions
        if: steps.changesets.outputs.published == 'true'
        run: |
          PACKAGE_VERSIONS=$(echo '${{ steps.changesets.outputs.publishedPackages }}' | jq -c 'map({name: .name, value: .version}) | from_entries')
          echo "packageVersions=$PACKAGE_VERSIONS" >> $GITHUB_OUTPUT

      - name: rootage-artifacts가 배포된 경우 Slack에 알려요
        if: steps.changesets.outputs.published == 'true' && contains(fromJson(steps.changesets.outputs.publishedPackages || '[]').*.name, '@seed-design/rootage-artifacts')
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "새 Rootage 버전이 배포되었어요."
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: "새 Rootage 버전이 배포되었어요: v${{ fromJson(steps.get-package-versions.outputs.packageVersions || '{}')['@seed-design/rootage-artifacts'] }}"
              - type: "section"
                text:
                  type: "plain_text"
                  text: "문서 빌드까지는 시간이 조금 더 걸릴 수 있어요."
              - type: "actions"
                elements:
                  - type: "button"
                    style: "primary"
                    text:
                      type: "plain_text"
                      text: "Changelog"
                    url: "https://seed-design.io/react/updates/changelog"
